### ISSUE TITLE
Please add hawaii kernel to all next distributives

### ISSUE THREAD

**Issue by Quake4** [andru-kun/wildrig-multi#1]

**Comment by platinum4** [comment]
idk, I can't get this to work no matter what combination of settings I try, stock BIOS stock clocks, --opencl-launch 16(thru)20x256, --opencl-threads 1(thru) 3
Nothing works longer than 60 seconds

**Comment by andru-kun** [comment]
@Quake4 problem is Hawaii kernel is too big, and I can't strip unused section from it to make it smaller(some bug in disassembler/assembler), so till that will be fixed, Hawaii kernel won't be in official package

**Comment by andru-kun** [comment]
@platinum4 did you try to run only one gpu using "--opencl-devices 0" ? And what algo?

**Comment by platinum4** [comment]
yes just one GPU only
bcd, bitcore, c11, etc.

**Comment by Quake4** [comment]
@andru-kun thanks.
@platinum4 launch start trying from 12x0

**Comment by andru-kun** [comment]
@platinum4 and what if set --opencl-threads 2 while using 14x256 for --opencl-launch? Anyway, Hawaii kernel more like AS IS solution in wildrig. Those cards are too old and need special techniques for optimizations, and I have no any to develop for them.

**Comment by platinum4** [comment]
threads 2 crashes but maybe due to crazy overclock for eth/cn
