### ISSUE TITLE
Help wanted experiential purpose only

### ISSUE THREAD

**Issue by Saikatsaha1996** [andru-kun/wildrig-multi#122]
I am trying to run miner in Aarch64 android device with OpenCL support but know not working with android .. can you give me aarch64 version? 

Android OpenCL GPU working fine with Xmrig

![Screenshot_2022-05-10-20-44-12-218_com termux](https://user-images.githubusercontent.com/72664192/167662957-3939a563-1af3-4b19-a727-0a4ee4ed4500.jpg)

![Screenshot_2022-05-10-19-58-19-536_com termux](https://user-images.githubusercontent.com/72664192/167663240-efbdbe2e-f82b-4198-b027-2af36369c81a.jpg)

**Comment by andru-kun** [comment]
sorry man, but no :) This needs too much work, and I use binary kernels, not just OpenCL runtime compiling, so no way I will support all variaty of gpu's on arm architecture.

**Comment by Saikatsaha1996** [comment]
> sorry man, but no :) This needs too much work, and I use binary kernels, not just OpenCL runtime compiling, so no way I will support all variaty of gpu's on arm architecture.

Okay man no problem 🤠! Just for testing purpose only 🐱
