### ISSUE TITLE
v0.31.3 / Skein2: No error when GPU stops mining

### ISSUE THREAD

**Issue by UselessGuru** [andru-kun/wildrig-multi#130]
My memory OC was too high.
WildRig starts mining OK for a few minutes, then dies.
Unfortunately miner does not display warning, just pretends to continue mining with 0 hash rate

**Comment by UselessGuru** [comment]
Nvidia GTX-750

**Comment by andru-kun** [comment]
it just hanged, for nvidia you can use --watchdog parameter for restart of miner
