### ISSUE TITLE
0.31.8 / v0.31.9: Error Not found default opencl-launch for NVIDIA GeForce GT 1030...

### ISSUE THREAD

**Issue by UselessGuru** [andru-kun/wildrig-multi#138]
Affected algos tested so far:
- AstralHash
- Bmw512
- C11
- CurveHash
- Dedal
- GhostRider
- HeavyHash
- HMQ1725
- JeongHash
- Lyra3v3
- MegaBTX
- MegaMec
- PadiHash
- PavelHash
- Phi
- SHA256csm
- Skein
- Skunk
- Tribus
- x16r
- x16rt
- x16s
- x17
- x21
- x22i

Mining still works though.

**Comment by andru-kun** [comment]
hmm, can you show me the arch of this gpu(gray label on initialization)? Looks like those cards are not "gtx 1030" )

**Comment by UselessGuru** [comment]
###################################
 #################  ################
 ################    ############### * ABOUT:    WildRig/0.31.8 libuv/1.21.0 OpenCL/2.0 MSVC/2015
 ####   #########    #########   ### * CPU:      Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
 ####     #######    #######     ### * ALGO:     skein2
 ####   #  ######    ######      ### * POOL #1:  skein2.eu.mine.zpool.ca:5233
 ####   ##  #####    #####  ##   ### * API PORT: 4005
 ####   ##   #####  #####   ##   ### * COMMANDS: hashrate, statistics, pause, resume
 ####   ##   #####  #####  ###   ###
[13:06:50] Not found default opencl-launch for NVIDIA GeForce GT 1030...
 ####   ###  #####  #####  ###   ###   donation: 1%
 ####   ###  ####    ####  ###   ###   send-stale: no
 ####   ###   ###    ###   ###   ###   watchdog: enabled
 ####   ##    ##      ##    ##   ###   temp limits: 60C..85C
 ####      #####  ##  #####      ###
 ####   #   ###  ####  ###   #   ###
 ####   ##       ####       ##   ###
 ####   #####  #      #  #####   ###
 ####   #####  ###  ###  #####   ###
 ####                            ###
 ############   ##  ##   ###########
 #############   #  #   ############
  #############        #############
      ###########    ###########
          ##################

[13:06:51] initializing GPUs...
[13:06:51] PTX ISA: 7.7
[13:06:51] GPU #1: NVIDIA GeForce GT 1030 [busID: 12] [arch: sm61]
[13:06:51] threads: 1, intensity: 18, worksize: 256/1024, cu: 6, mem: 2047Mb
