### ISSUE TITLE
Not connect to pool without extranonce

### ISSUE THREAD

**Issue by kr1z1s** [andru-kun/wildrig-multi#14]
![image](https://user-images.githubusercontent.com/5347595/57618238-8bed4f00-758b-11e9-8513-734ae8cb839d.png)
Please, add the option to disable extranonce

**Comment by andru-kun** [comment]
Check 0.16.3, I have added --no-extranonce parameter

**Comment by kr1z1s** [comment]
Thank!
But, after autorization miner not working
![image](https://user-images.githubusercontent.com/5347595/57650126-b6162f80-75d2-11e9-939d-f89b37af672e.png)

**Comment by andru-kun** [comment]
this is something else, because there is no new job messages. Port and wallet is correct? If so, I will check this pool tomorrow

**Comment by kr1z1s** [comment]
This my p2pool nodes.

p2p-south.xyz:7011 - Bitsend node

another miner with z-enemy (nvidia)  everything works correctly

This problem is only with your miner. Other AMD (phancy teamred) miners work well

**Comment by andru-kun** [comment]
can you use *--print-debug --log-file log.txt* and post logs here?

**Comment by kr1z1s** [comment]
[log.txt](https://github.com/andru-kun/wildrig-multi/files/3174733/log.txt)

**Comment by andru-kun** [comment]
Yep, pool violating some standards, sending random id's in json messages %) Will check what can I do with this on my side.

**Comment by kr1z1s** [comment]
yes yes
i send random work ID...

`        jobid = str(random.randrange(2**128))
`

**Comment by andru-kun** [comment]
fixed, will provide build today. Problem was that I don't expect id at all when pool send message with "method" inside. Id expected only when subscribe, login and getting result accepted/rejected the share

**Comment by andru-kun** [comment]
sorry, release postponed a bit, because I was not able to finish some other things today

**Comment by andru-kun** [comment]
forgot to write here. 0.16.4 released and should fix the problem

**Comment by kr1z1s** [comment]
Thank you very much! I'm already informing users that you can now use your miner to mine on p2pool!
