### ISSUE TITLE
Lost card DATA in HIVEOS (Linux)

### ISSUE THREAD

**Issue by IAMANUMBER4** [andru-kun/wildrig-multi#143]
Lost fan, temperature and hashrate data that shows for a ten card rig in 31.8 mining on CURVEHASH, but does not show this information on 32.0 for the last 4 cards on AMD 10 card rig. Reverting to 31.8 solves this issue.

Only the first 6 cards show all data

**Comment by IAMANUMBER4** [comment]
![Screenshot 2022-07-09 103901](https://user-images.githubusercontent.com/108990533/178112749-78f1bf74-72e3-45ba-b331-43f76c877d56.png)
![Screenshot 2022-07-09 104112](https://user-images.githubusercontent.com/108990533/178112750-4c55f25b-7e48-47d9-8944-842dbf79b59e.png)

**Comment by andru-kun** [comment]
Yeah, known issue so far, will check it. But be sure - 0.32.0 is hashing on all of them

**Comment by IAMANUMBER4** [comment]
Thanks

**Comment by andru-kun** [comment]
Can you check 0.32.1 version if you still mining curvehash?
