### ISSUE TITLE
Upcoming DAG size reduction for VEIL ProgPow

### ISSUE THREAD

**Issue by us77ipis** [andru-kun/wildrig-multi#144]
We are planning to reduce the DAG size for [VEIL](https://github.com/Veil-Project/veil) ProgPow mining.

As far as I can see, mining software currently has hardcoded the rule for epoch derivation from the block height. Since the DAG size reduction will be done by changing the epoch, and to allow for more flexibility in the future, I would propose the following changes:
* Add another parameter to the `mining.notify` call of the stratum protocol implementation through which the mining software gets the current epoch number.
* If you (or T-Rex miner) currently have implemented some optimization for pre-computing DAGs near an epoch change, maybe we could also add a second additional parameter to `mining.notify` which specifies the epoch of the upcoming next block. Then, you can still pre-compute DAGs on GPUs with enough memory.

This (or a similar) solution would be preferable over hardcoding the epoch derivation changes in the mining software, as it allows for more flexibility in the future.

Once we agree on a solution, I can quickly setup a stratum server on a devnet where you can connect to for testing your WildRig implementation.

Thanks for your support.

**Comment by seanPhill** [comment]
Thanks! We are available for any questions and collaboration with Wildrig. 
support@veil-project.com is also another way to contact us.

**Comment by andru-kun** [comment]
since algorithm is already named progpow-veil, I guess no need in additional parameters. Just decide when hardfork happen, and I will use new DAG size after that block.

**Comment by us77ipis** [comment]
But then it would again be hardcoded in the mining software. As I mentioned above, we would like to have more flexibility in the future if possible.

**Comment by us77ipis** [comment]
And adding the parameter(s) to the `mining.notify` call shouldn't be much more difficult than hardcoding the change in the epoch derivation logic, I think :thinking:.

**Comment by andru-kun** [comment]
as I see in your code changes, you have nHeightProgPowDAGSizeReduction and changed ETHASH_EPOCH_LENGTH. So this will need hardcode anyway, or more parameters.

**Comment by us77ipis** [comment]
Why? Which other parameters do you need? If you get the epoch number from the stratum server, you don't need to calculate that number anymore, so you don't need `nHeightProgPowDAGSizeReduction` neither `ETHASH_EPOCH_LENGTH`, or am I missing something?

**Comment by andru-kun** [comment]
Oh, forgot that epoch is blockNumber divided by epochLength. Ok then, additional parameter will be fine.

**Comment by us77ipis** [comment]
So do you have implemented some DAG pre-computing in WildRig (or planned to do so in the future), and thus need the second additional parameter to know the epoch of the next block too or not?

**Comment by andru-kun** [comment]
Nope, I don't pre-compute anything, but this parameter definitely needed for other miners, since some of them do compile new kernel.

**Comment by us77ipis** [comment]
Okay, and do you know if the other miners pre-compute it only one block before the epoch change or already multiple blocks before? Because if miners need more flexibility for this optimization, instead of sending the epoch of the next block as second parameter, we could also do the following:
* Add a second parameter which is the next epoch.
* Add a third parameter which is the height at which the next epoch change is going to happen.
That would allow for maximum flexibility on both sides.

**Comment by seanPhill** [comment]
Thanks for the response! :) Do we need a prerelease WildRig version for testing? @us77ipis @andru-kun 
And is it possible for me to test on my Mac? (Which is a Mac Pro late-2013, with two 3GB AMD FirePro D500 GPUs, and given the age, it's currently on macOS 12.4 (the latest macOS, but the last this will ever run on). 

I suppose that WildRig uses OpenCL (and does not support Apple's Metal framework)? version: ?
These GPUs are as follows, and 

  Chipset Model:	AMD FirePro D500
  Type:	GPU
  Bus:	PCIe
  PCIe Lane Width:	x16
  Metal Family:	Supported, Metal GPUFamily macOS 2

I'm no expert on GPUs, but my System information shows

OpenCL:
  Version:	4.7
  Obtained from:	Unknown
  Last Modified:	9/5/2022, 4:30 pm
  Get Info String:	4.7, Copyright 2008-2019 Apple Inc.
  Location:	/System/Library/Frameworks/OpenCL.framework
  Private:	No

I don't know if any of this indicates I can try WildRig on it (if the DAG is below 3GB), or maybe I have to boot in LINUX (Ubuntu)?

**Comment by us77ipis** [comment]
I think @andru-kun can test it. I can setup a test stratum server connected to the devnet for the testing.

**Comment by us77ipis** [comment]
> so looking forward for a test stratum.

@andru-kun I sent you an email with the test stratum server connection details.

**Comment by andru-kun** [comment]
Tests are done, everything works fine, changes will be available in the next release :)

**Comment by us77ipis** [comment]
Thanks @andru-kun for the quick replies and implementation!

**Comment by andru-kun** [comment]
changes done in 0.32.1
