### ISSUE TITLE
Odocrypt algo for Digibyte support

### ISSUE THREAD

**Issue by kr1z1s** [andru-kun/wildrig-multi#15]
in July on Digibyte fork to new algo Odocrypt.

Inside Odocrypt - Keccak. 

Hash - https://github.com/dgb256-online/odo-miner/tree/master/src/crypto

But, algo regularly change. 

Exemple for FPGA - https://github.com/dgb256-online/odo-miner/blob/master/src/autocompile.sh

Loop this - https://github.com/dgb256-online/odo-miner/blob/master/src/autocompile.sh#L52

**Comment by andru-kun** [comment]
well, this algo is very fast on FPGA, so no sense to make it for GPU, as it was with algorithms vBlake(VeriBlock coin) and bmw512(XDN coin). Profit will be for a couple of days, if not less. And considering fact that Digibyte is pretty huge - FPGA's will be ready at start with full power, so...
