### ISSUE TITLE
Hoe description supports lyra2v2 algorithm. Why can't I find this algorithm in hive OS settings

### ISSUE THREAD

**Issue by paopao-tang** [andru-kun/wildrig-multi#151]
![QQ图片20220821160349](https://user-images.githubusercontent.com/98439879/185781883-d2e7d209-8df7-46d5-a80b-49f5d3462ec8.png)

**Comment by paopao-tang** [comment]
@andru-kun

**Comment by andru-kun** [comment]
this is a question to HiveOS dev team. But you can choose any algorithm there and put *--algo lyrav2v2** to Extra Parameters. Anyway, this algorithm is mineable by ASICs. so not much sense.

**Comment by paopao-tang** [comment]
![QQ图片20ss2412](https://user-images.githubusercontent.com/98439879/185782520-681bfde8-3fe0-4076-9ac4-2adeab32a356.png)
It still can't operate normally, and it's not possible to remove the *

**Comment by paopao-tang** [comment]
I have tried to choose other similar algorithms, but the mine pool did not accept them

**Comment by andru-kun** [comment]
> ![QQ图片20ss2412](https://user-images.githubusercontent.com/98439879/185782520-681bfde8-3fe0-4076-9ac4-2adeab32a356.png) It still can't operate normally, and it's not possible to remove the *

omg, man... if you can't copy text correctly from your browser then I can't help you here. Try this: --algo lyra2v2
Anyway, I'm closing the issue.
