### ISSUE TITLE
R9 390x stuck at initialization

### ISSUE THREAD

**Issue by pedro02220** [andru-kun/wildrig-multi#157]
![imagem_2022-09-18_140112459](https://user-images.githubusercontent.com/85848466/190903345-51e79e7a-0322-411d-ad57-a3293fdd7d92.png)
 how do i fix this?

**Comment by andru-kun** [comment]
No need to do anything with this message. HiveOS just uses old parameter I don't provide anymore, so miner just ignore it.

**Comment by pedro02220** [comment]
but it doesnt mine for some reason

**Comment by andru-kun** [comment]
> but it doesnt mine for some reason

Then I need more details. What gpu's, what parameters, etc.?

**Comment by pedro02220** [comment]
well im using a R9 390x with core state 4 and thats it 
 it just says "unrecognized option "--donate-level=1"
i tried using the same version on windows and it doesnt have that problem

**Comment by andru-kun** [comment]
looks like something to do with initializing devices, it just stuck there, have no idea why

**Comment by andru-kun** [comment]
can you call ``/hive/miners/wildrig-multi/0.32.2/wildrig-multi --print-devices`` from HiveOS console?

**Comment by pedro02220** [comment]
![image](https://user-images.githubusercontent.com/85848466/190925763-f73b60d6-c100-49b2-9330-5d596c661724.png)
 i restarted the miner now and its mining, idk what was happening before i only that the print screen i took there was after like 20 minutes waiting

**Comment by pedro02220** [comment]
at least it was creating the dag on the gpu

**Comment by andru-kun** [comment]
> at least it was creating the dag on the gpu

nah, it's creating a dag after ``new job`` message, something to do with initialization stage, probably because of using different miner before, have no idea. At least it works now :)

**Comment by pedro02220** [comment]
im still waiting to see if starts mining, but i think i know the problem its around the os and not the miner, im gona try and remake the usb with a fresh new hive os, if it solves that ill tell you something :)
