### ISSUE TITLE
very long time initializing GPUs

### ISSUE THREAD

**Issue by tymoteuszrogalewski** [andru-kun/wildrig-multi#159]
what may be the reason of very long start miner on 11xNVIDIA 3080 ?

[08:35:40] initializing GPUs...
[08:35:42] PTX ISA: 7.6
[08:35:42] GPU #0: NVIDIA GeForce RTX 3080 [busID: 1] [arch: sm86] 
[08:35:42] threads: 1, intensity: 1024, worksize: 256/1024, cu: 68, mem: 10017Mb
[08:36:45] GPU #1: NVIDIA GeForce RTX 3080 [busID: 4] [arch: sm86] 
[08:36:45] threads: 1, intensity: 1024, worksize: 256/1024, cu: 68, mem: 10018Mb
[08:37:49] GPU #2: NVIDIA GeForce RTX 3070 [busID: 6] [arch: sm86] 
[08:37:49] threads: 1, intensity: 1024, worksize: 256/1024, cu: 46, mem: 7982Mb
[...]

As you can see - about 1 minute per 1 GPU. Rig with 11 GPUs...starting about 11 minutes, sometimes even longer.

During this process CPU is 100% used by wildrig-multi process and after loading/during minig theare two processess of wildrig-multi with about 30% CPU usage for each one.

Intel(R) Pentium(R) CPU G4560T @ 2.90GHz
ASUSTeK COMPUTER INC. B250 MINING EXPERT Rev X.0x
RAM 8 GB

using newest version 0.32.2
ubuntu 18
kernel 5.10.60
NV drivers 510.73.05
miner options:
--algo ghostrider --url stratum+tcp://x:x --user x --pass x

our client says that under Windows its working ok and fast loading.

**Comment by andru-kun** [comment]
this question can be sent directly to NVIDIA :) For some reason after using CUDA miners, OpenCL one will initialize too damn long. Every next start will be fine, but if start CUDA miner(or any other CUDA software I guess) - it will back initialization to longtime again.

**Comment by andru-kun** [comment]
> During this process CPU is 100% used by wildrig-multi process and after loading/during minig theare two processess of wildrig-multi with about 30% CPU usage for each one.

This one is odd, TaskManager should show only one wildrig.exe(and probably some Console Window Host stuff on Win10/Win11). Did you check this on Details tab?

**Comment by tymoteuszrogalewski** [comment]
Linux, Linux, Linux!!! not the .exe :)

**Comment by tymoteuszrogalewski** [comment]
<img width="559" alt="Zrzut ekranu 2022-09-21 o 12 50 31" src="https://user-images.githubusercontent.com/45815746/191485893-9511eade-0de8-4a22-b94e-d4f8e1a07d27.png">
<img width="734" alt="Zrzut ekranu 2022-09-21 o 12 50 13" src="https://user-images.githubusercontent.com/45815746/191485901-a07f44cf-456b-493f-b4ec-e333f316bc81.png">

**Comment by andru-kun** [comment]
> Linux, Linux, Linux!!! not the .exe :)

oh, sorry, missed that one at the end ) Maybe you start it once and closed as a hanged one, but it still there? :)

**Comment by tymoteuszrogalewski** [comment]
nope. our system (SimpleMining) first shut down old process and..I checked twice that in this moment there is no one wildrig process running. And then start running new process. ps ax shows two processess but pstree show that only one process is runing with 8 childs?

**Comment by andru-kun** [comment]
8 childs? I'd say maybe this is 1 thread per GPU(something to do with nvidia drivers/etc.), but you have 11, so this is something I still have no idea what :)

**Comment by andru-kun** [comment]
latest versions should start much faster on most algorithms
