### ISSUE TITLE
Closing WildRig 0.17.n crashes AMD driver (Windows)

### ISSUE THREAD

**Issue by UselessGuru** [andru-kun/wildrig-multi#16]
Closing the WildRig miner crashes the AMD driver. The error in the event (system) log is 

```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Display" /> 
  <EventID Qualifiers="0">4101</EventID> 
  <Level>3</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2019-06-10T14:50:22.017128100Z" /> 
  <EventRecordID>23384</EventRecordID> 
  <Channel>System</Channel> 
  <Computer>BlackBox</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>amdkmdap</Data> 
  <Data /> 
  </EventData>
  </Event>
```

This freezes the computer for approx 10 seconds until the driver recovers. The issue happens with newer AMD drivers (I am currently on 2841.5)

**Comment by andru-kun** [comment]
Have no idea why it happens. Did you try to run gpu in stock?

**Comment by UselessGuru** [comment]
> Did you try to run gpu in stock?

I reduced the GPU core by 25MHz... stable now. 👍 
It is interesting that running the GPU at higher clock is fine with all miners, and so is exiting, only wildrig crashes.... 
Anyway, the issue is solved for me.
