### ISSUE TITLE
Unsupported method: "job" when mining raptoreum

### ISSUE THREAD

**Issue by jcpieper** [andru-kun/wildrig-multi#163]
![message](https://user-images.githubusercontent.com/37374279/193369028-256cf876-d269-4202-9fa5-5ae71039e991.png)
Hello,
I get the above message when mining to pool with my RX580 8 gig. Pool is moneroocean.stream.
Thanks.

**Comment by andru-kun** [comment]
I think you are trying to mine some different algo but with raptoreum payments, that's why you get this unsupported messages.
