### ISSUE TITLE
If errorlevel 1000 goto custom meaning plz 

### ISSUE THREAD

**Issue by auroracoin** [andru-kun/wildrig-multi#166]
@echo off

:loop
wildrig.exe --print-full --algo ghostrider --url stratum+tcps://us.flockpool.com:5555 --user myRTMaddress --pass x

if ERRORLEVEL 1000 goto custom
timeout /t 5
goto loop

:custom
echo Custom command here
timeout /t 5
goto loop

Shouldn't       if ERRORLEVEL 1000 goto custom  be    if ERRORLEVEL 1 goto custom  ?
Why 1000 ? 
thx

**Comment by andru-kun** [comment]
Hmm, looks like you are right. I forgot to change that. Thanks, will fix in future releases.

**Comment by auroracoin** [comment]
Ok thx :)

**Comment by andru-kun** [comment]
fixed since 0.33.7
