### ISSUE TITLE
Nvidia GeForce 522.25 WHQL lower heavyhash performance.

### ISSUE THREAD

**Issue by xdmsx** [andru-kun/wildrig-multi#170]
Nvidia GeForce 522.25 WHQL lower heavyhash performance of 3070Ti from 600 to 160 MH/s. Is it possible to fix?

**Comment by andru-kun** [comment]
can you show screenshot of initialization stage? Probably wrong intensity set, idk, it works fine for me on 1660S with that drivers.

**Comment by xdmsx** [comment]
intensity 27, worksize 256/1024 in case screen not loading. And versions of miner I used was latest and one before it.
https://www.dropbox.com/s/377zkno37uwzrdp/12.02.23.png?dl=1

**Comment by andru-kun** [comment]
what about 0.32.2 version? But this looks strange, without having real card in system probably not possible to fix at all.

**Comment by xdmsx** [comment]
I just tried with 0.32.1 and it work fine, around 600 per card (have 3 in pc). Than i will use older miner version for now.

**Comment by xdmsx** [comment]
You should close the issue ow cause its just gone for unknown reason. New version works fine too.

**Comment by andru-kun** [comment]
interesting, looks like something to do with all that manipulation around mem lock/etc., anyway, good to hear it works :)
