### ISSUE TITLE
High Load Average

### ISSUE THREAD

**Issue by makoshark2001** [andru-kun/wildrig-multi#175]
I keep seeing really high load avg in hiveos running evrprogpow.

**Comment by andru-kun** [comment]
Any details? GPU's you are runnig? Average LA on other algorithms? High LA all the time or only some spikes?

**Comment by makoshark2001** [comment]
I am running nvidia gtx 1660's and 1660 supers on the two rigs that have the load,  its moderately high all the time but spikes higher.  Also it appears to only happen on 2 of m,y 4 rigs, the two it happens on are Intel cpu's my rigs with AMD cpu's do not do it. On the amd cpu rigs I am running 1650 supers and amd 5600 xt's . Also on the hive rig status page it sometimes show as if the hashrate stops and is not mining, but if i remote into the rig it shows that the gpu's are hashing. On all other algo's they are fine on load.

**Comment by andru-kun** [comment]
Can you specify exact model of CPU's? Some spikes are possible, since evrprogpow algorithm need new kernel for gpu each 3 blocks, and CPU is involved. But load all the time is strange. Also, how many GPU's in rig?

**Comment by makoshark2001** [comment]
Latest release 33.9,  one rig is Intel(R) Celeron(R) CPU G3900 @ 2.80GHz AES
other is  Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz AES

each of these are 6 gpu rigs
 

the AMD rigs that are not having the issue are AMD Ryzen 5 3600 6-Core Processor AES and AMD Phenom(tm) II X2 550 Processor
