### ISSUE TITLE
4gb cards dev session error on evrprogpow

### ISSUE THREAD

**Issue by makoshark2001** [andru-kun/wildrig-multi#176]
On my 4gb gpu's running evrprogpow I get an error when dev session starts and after that all errors on shares to the pool.  See attached images. 6gb gpu's work correctly.

<img width="900" alt="error1" src="https://user-images.githubusercontent.com/2223726/201703503-43cfe2af-2bbb-4bb1-9997-1a69f9ae9d82.png">
<img width="600" alt="error2" src="https://user-images.githubusercontent.com/2223726/201703533-d32bc9de-a183-402d-964c-95c279d98f6c.png">

**Comment by andru-kun** [comment]
yep, found an issue with logic when devfee dag doesn't cache, thanks for the report, fixed already, will release new version in a few hours.

**Comment by andru-kun** [comment]
should be fixed in 0.34.0, HiveOS script to update your 0.33.9 version

`cd /hive/miners/wildrig-multi/0.33.9 && wget https://github.com/andru-kun/wildrig-multi/releases/download/0.34.0/wildrig-multi-linux-0.34.0.tar.xz && tar -xf wildrig-multi-linux-0.34.0.tar.xz`
