### ISSUE TITLE
Set up memory lock and core lock

### ISSUE THREAD

**Issue by leewachu** [andru-kun/wildrig-multi#178]
Can we set up memory lock and core lock on Wildrig-multi to reduce volts con Nvidia ? Thanks

**Comment by Canefis** [comment]
The most needed question

**Comment by andru-kun** [comment]
No, but you can use 3rd party tools, like nvtool or nvidia-smi. And use them with --execute parameter. Just check discord pinned messages for instructions.

**Comment by Canefis** [comment]
> No, but you can use 3rd party tools, like nvtool or nvidia-smi. And use them with --execute parameter. Just check discord pinned messages for instructions.

Where I can check pinned message, I cannot find (understand), thank you

**Comment by andru-kun** [comment]
Try 0.38.0, there is --gpu-core-clock and other parameters(see help), So far fully supported only NVIDIA RTX cards
