### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by luc1an24** [andru-kun/wildrig-multi#18]
Hi

I have a request for you.
It would be really helpful if you could implement these features to the miner:
a) A flag to list all devices (like --list or something like that) with their data (index, bus Id, name)
b) Power usage reporting in API

Thank you for your time!

PS: If any of these features is already implemented please point me in the right direction

**Comment by andru-kun** [comment]
hi, try 0.17.9 build, there is parameter --print-devices(previously was only --print-platforms). What about power usage - this is old story... still in TODO list adding temperature monitoring, and power usage is even more complicated. Right now have no plans for that, but you can create separate issue for this so I will see it time to time and finally implement some day :)
