### ISSUE TITLE
0.35.1 beta2 amd problems with nexapow

### ISSUE THREAD

**Issue by ovenmittromney** [andru-kun/wildrig-multi#181]
AMD cards (5600, 5700, etc) get half hash or less when on mixed rigs with nvidia cards in linux on nexapow. This doesn't make sense - they hash normally on amd-only rigs.

Also, RX6600/6600xt are bugged, with only 2-4mh on linux, 15mh on windows.  

67-68-69xt work normally.

**Comment by andru-kun** [comment]
This is a bug of HiveOS as far as I see, happens only on it. Someone get it fixed with Gen.3 mode for gpu's in BIOS.

**Comment by andru-kun** [comment]
this is HiveOS bug. You need to update HiveOS and amd drivers, use this instructions
1. you need latest HiveOS iso to be installed(at least hiveos-0.6-219-stable@220928) so amdgpu-pro OpenCL will be 21.40.1-5.13.2208
2. update HiveOS via upgrade button(at least to 0.6-220@221221, better to use the latest one)
3. run command amd-ocl-install 22.20
