### ISSUE TITLE
AMD GPU Hive issue

### ISSUE THREAD

**Issue by Shar2** [andru-kun/wildrig-multi#183]
Для смешанных/красных ригов наблюдается проблема - первые 2 карты работают не полностью
Nexapow
![image](https://user-images.githubusercontent.com/49821454/207460492-905e0635-f834-4749-af65-0666fe76f353.png)
![image](https://user-images.githubusercontent.com/49821454/207460528-6bf38057-3239-4215-8d64-90a5fb93c16e.png)

**Comment by andru-kun** [comment]
Известная проблема, повторяется пока только на HiveOS в паре с AMD, и зачастую на китайских материнских платах. Некоторым помогает поставить в BIOS настройку Gen.3 для PCI-E.

**Comment by ovenmittromney** [comment]
This isn't a pci-e problem, this is a your miner problem. No other miner has this bug.

**Comment by andru-kun** [comment]
> This isn't a pci-e problem, this is a your miner problem. No other miner has this bug.

Yeah, probably you are an expert, but well, same issue happens with srbminer, and this happens only on HiveOS. This is some combination of miner code and driver issue, but I have no idea what exact reason so far.

**Comment by itvalentino76** [comment]
Exactly same problem on skydoge, on latest beta.

**Comment by ovenmittromney** [comment]
> Exactly same problem on skydoge, on latest beta.

because its a miner issue

**Comment by itvalentino76** [comment]
> > Exactly same problem on skydoge, on latest beta.
> 
> because its a miner issue

Yes, we get it. Does your opinion solve the problem? Dev , please solve the issue. Same issue was present few years ago on srb, but solved.

**Comment by andru-kun** [comment]
> Dev , please solve the issue. Same issue was present few years ago on srb, but solved.

No, this problem still persist for srb, and it's random. Anyway, I will work on this,

**Comment by itvalentino76** [comment]
Thank you, if you need testing, email me. itvalentino76@gmail.com

**Comment by itvalentino76** [comment]
Checked, the issue is the almost the same with x16rt algo (avian) , nut only 20% less on first 2 cards

**Comment by itvalentino76** [comment]
actually is going down after, same on x16rt as in other 2 algos. Seems like a serious global problem.

**Comment by andru-kun** [comment]
this is HiveOS bug. You need to update HiveOS and amd drivers, use this instructions
1. you need latest HiveOS iso to be installed(at least hiveos-0.6-219-stable@220928) so amdgpu-pro OpenCL will be 21.40.1-5.13.2208
2. update HiveOS via upgrade button(at least to 0.6-220@221221, better to use the latest one)
3. run command amd-ocl-install 22.20

**Comment by itvalentino76** [comment]
Now with the latest driver, it is mining with only one card

**Comment by Serg-19712023** [comment]
I have the same problem on an ASRock H510 Pro
![photo_2023-01-14_19-03-28](https://user-images.githubusercontent.com/122687349/212481640-a7c85960-0d28-49f7-acad-2ac1430f1af7.jpg)
![photo_2023-01-14_19-03-59](https://user-images.githubusercontent.com/122687349/212481641-63e3ef18-65b2-453b-a14d-40ed54a95daf.jpg)
BTC+ motherboard with 5700Xt and W5500 graphics cards
