### ISSUE TITLE
I require immediate support for ARC https://advtech.group/

### ISSUE THREAD

**Issue by claudiodelf** [andru-kun/wildrig-multi#187]
I require immediate support for ARC 
https://advtech.group/
https://miningpoolstats.stream/advtechcoin
wildrig on x11 algorithm only works for nvidia

**Comment by andru-kun** [comment]
immediate? xD This is kinda rude ) But anyway, I can't buy them in Ukraine right now, so it's hard to make a support.

**Comment by andru-kun** [comment]
Immediate? xD It's kinda rude ) But anyway, wildrig support x11 on all gpu's it support. Problem is x11 for ASIC's, not for gpu's

**Comment by claudiodelf** [comment]
> Immediate? xD It's kinda rude ) But anyway, wildrig support x11 on all gpu's it support. Problem is x11 for ASIC's, not for gpu's

Sorry for immediate I did a copy paste referring to the pool rplant. You see I'm already mining it with nvidia gpu's with wildrig algo x11 it's okay.

**Comment by andru-kun** [comment]
done since version 0.38.0 )
