### ISSUE TITLE
Impossible to start the miner on Windows

### ISSUE THREAD

**Issue by M0rT4L13** [andru-kun/wildrig-multi#188]
Hello !

Here's my error : 
![Capture](https://user-images.githubusercontent.com/121009175/208368208-bddc9409-6bc1-480c-b461-613e4a001892.JPG)

what can i do ? I can't close the audinate dll cause my computer using it

**Comment by andru-kun** [comment]
Protection subsystem of miner doesn't like apps that inject their dll's, so no way to mine on such PC's right now.
