### ISSUE TITLE
Are Polaris cards supported on Nexapow 

### ISSUE THREAD

**Issue by Capt-Poopins** [andru-kun/wildrig-multi#189]
I think I read on earlier version that AMD cards on linux weren't supported yet but are with V 0.35.3
Im using hiveos and tried to mine Nexa and the miner works fine I just am not getting accepted shares. If I missed something or they arent supported I apologize for wasting time.

**Comment by andru-kun** [comment]
They are supported, but you need to update your drivers to 21.40. For some reason 20.40 doesn't work

**Comment by Capt-Poopins** [comment]
Thank you that did it.
