### ISSUE TITLE
Benchmark timeout

### ISSUE THREAD

**Issue by luc1an24** [andru-kun/wildrig-multi#19]
Hi

Is there any way that you could implement timeout for Benchmark process?
Currently it is displayed every 60s, but you could add a flag --benchmark-timeout, which would accept parameter in seconds for how long benchmark should run and then display avg. hashrate.
After timeout you could close the miner.
This would really help me on integrating your miner to NiceHash.

Thank you!

**Comment by andru-kun** [comment]
Hi, right now there is only --print-time(in seconds) parameter that can help you. But ok, --benchmark-timeout or something like that is a good idea, I will implement it in next release.

**Comment by luc1an24** [comment]
Thank you for your help!
