### ISSUE TITLE
No tail for GPUs with errors 

### ISSUE THREAD

**Issue by Nikovash** [andru-kun/wildrig-multi#190]
When looking at the tail for the miner I can see that occasionally error in shares happen, but what I do not see is what card is presenting the problems

This seems like a simple fix as most other miners out there address this in multiple ways. if Using hive OS if a GPU becomes so unstable it goes offline you can make the assumption that it is that card that is causing the problem, but it is still just an assumption

For debugging or stabilizing cards this would be incredibly helpful

![Screen Shot 2022-12-20 at 7 36 45 PM](https://user-images.githubusercontent.com/67256882/208815729-3b8a8792-5e0f-4d5b-8ad8-84b832f47adb.png)

**Comment by andru-kun** [comment]
just set your color theme to normal, or make everything white or inverse ) There is GPU id when you see reject. Same for accepted share

**Comment by Nikovash** [comment]
only in the live tail, who tf is going to sit there for 24 hours watching a live tail, vs every other miner puts an accepted percentage next to the gpu Example:


01:00.    03:00
41C.       40C
49%.      49%
74w.       79w
100%.     54.66%

see pretty easy to watch it at any point and time and see what is going on

**Comment by andru-kun** [comment]
since 0.36.1 should be visiable all statistics per GPU
