### ISSUE TITLE
 skydoge: Windows users are using ccminer 2.5.3.1 because it is a 40 % more powerful in series 3000

### ISSUE THREAD

**Issue by jomual0** [andru-kun/wildrig-multi#192]
Hi Andru,

Could you improve this algorithm because ccminer version 2.5.3.1 has increased hash in all GPU's and nobody is going to use your miner if linux version is done.

Regards,

**Comment by UselessGuru** [comment]
>  because ccminer version 2.5.3.1 

Where did you get this miner`? Download link please.

**Comment by andru-kun** [comment]
> > because ccminer version 2.5.3.1
> 
> Where did you get this miner`? Download link please.

check their discord :)

What about optimizations - unfortunately I won't do any, too old hashfuncs and too much work.
