### ISSUE TITLE
#183 update driver on amd mining with only one card

### ISSUE THREAD

**Issue by itvalentino76** [andru-kun/wildrig-multi#193]
Hello, after updating to latest amd 22.20 , under hiveos, it is mining with only one card. Skydoge.

**Comment by itvalentino76** [comment]
<img width="925" alt="sky" src="https://user-images.githubusercontent.com/5484844/210731441-ca5c24fd-6094-4b2b-93d5-ac26ab484180.png">

**Comment by andru-kun** [comment]
Probably because of wrong following the instructions. For proper AMD driver install you need to install final HiveOS image first and only then upgrade and amd driver install

**Comment by itvalentino76** [comment]
You mean newer kernel? Otherwise I followed exactly your instructions. I will try installing newer kernel - 5.10.0 #110 and get back

**Comment by andru-kun** [comment]
> You mean newer kernel? Otherwise I followed exactly your instructions. I will try installing newer kernel - 5.10.0 #110 and get back

Try to use `hive-replace -l` and install first variant
`1) hiveos-0.6-219-stable@220928.img.xz · Latest Stable · K 5.10.110 · N 510.73.05 · A OpenCL 21.40.1-5.13.2208 · Dual-Boot / Image with support for latest Nvidia GPUs and AMD GPUs.`

**Comment by itvalentino76** [comment]
yes, worked , thank you

**Comment by Serg-19712023** [comment]
> 

I did. As a result, only 2 cards out of 6 work.
