### ISSUE TITLE
Disable GPU

### ISSUE THREAD

**Issue by carlossulato** [andru-kun/wildrig-multi#194]
Sorry if I didn't find it, I've tried looking everywhere but I couldn't find the command to disable one of the GPUs.

**Comment by Stey-U** [comment]
Add the argument --opencl-devices (then the number of the GPU you want to use and add a comma inbetween each GPU number if your want to use more than one GPU)  0,1,2,3,4 to the startup .bat file; for an example "wildrig.exe --opencl-devices 0,1,2 --algo nexapow --url stratum+tcp://stratum-eu.rplant.xyz:7092 --user nqtsq5g5m0lbdt90gycpshe2mzwnjscl0tz28sgp9gj65wgh --pass x". The --opencl-devices 0,1,2 part tells it to only use the first, second and third GPU.

**Comment by carlossulato** [comment]
Thanks, it worked!
