### ISSUE TITLE
error 红字报错

### ISSUE THREAD

**Issue by xzn2198968** [andru-kun/wildrig-multi#203]
Error CL_MEM_OBJECT_ALLOCATION_FAILURE when calling clenqueue NDRangekernel for kernel '*****'
一直报错

win10 1903  
3060TI
驱动528.02 512

**Comment by xzn2198968** [comment]
![photo_2023-01-16_15-07-05](https://user-images.githubusercontent.com/111621803/212658260-c6a4f9d1-b2ff-41bd-8c02-4b8587f974aa.jpg)

**Comment by xzn2198968** [comment]
The same error is reported when I use - D to enable only one graphics card

**Comment by andru-kun** [comment]
You need Windows 10 at least build 2004 or newer and set Virtual Memory to 9Gb per GPU.

**Comment by xzn2198968** [comment]
> 您至少需要 Windows 10 build 2004 或更新版本，并将虚拟内存设置为每个 GPU 9Gb。

Thank you.
