### ISSUE TITLE
Проблема с картами RX6600XT 

### ISSUE THREAD

**Issue by kace77** [andru-kun/wildrig-multi#204]
![nexa](https://user-images.githubusercontent.com/80420906/212685518-dfb0a6b4-abc8-4b29-9c3b-9203e0876b01.jpg)
![nexa2](https://user-images.githubusercontent.com/80420906/212685684-4d92b0f1-923c-4dab-b97d-b20b3f428a3c.jpg)
Как не пытался, не могу ничего исправить.
Система чистая, после hive-replace -s и selfupgrade
Пытался ставить новые драйвера amd-ocl-install 22.10 и 22.20 - с ними вообще не работает.

**Comment by andru-kun** [comment]
> с ними вообще не работает
что тут имеется ввиду? Для 6000й серии нужен последний стабильный хайв(``hive-replace -s``), обновление из интерфейса, и установка дров 22.20 командой ``amd-ocl-install 22.20``. Если не находит после этого карточки - это одна проблема, тут не помогу. Если хешрейт n/a, то тут только снизить частоту ядра или поднять вольтаж.

**Comment by kace77** [comment]
![nexa3](https://user-images.githubusercontent.com/80420906/212718933-f69b5a37-bf8f-4a10-8d30-f661f58c2d04.jpg)
![nexa4](https://user-images.githubusercontent.com/80420906/212718944-86f6cc21-90d4-40b2-8920-8c3fe14c5cde.jpg)

Вот что после команды amd-ocl-install 22.20  и перезагрузки, выдает ошибку:

:0:rocdevice.cpp            :2652: 0158665123 us: 16545: [tid:0x7fab0ba96700] Device::callbackQueue aborting with error : HSA_STATUS_ERROR_ILLEGAL_INSTRUCTION: The agent attempted to execute an illegal shader instruction. code: 0x2a

**Comment by andru-kun** [comment]
это переразгон, как и писал собственно. Драйвера для 6000й серии так падают )

**Comment by kace77** [comment]
![nexa5](https://user-images.githubusercontent.com/80420906/212721539-918e386d-44ce-45e3-861d-8ecde64ccf02.jpg)

Поднял напряжение ядра на 50 мв(до 750), все стало на свои места, большое спасибо.
