### ISSUE TITLE
Solo Mining

### ISSUE THREAD

**Issue by nessuz** [andru-kun/wildrig-multi#206]
Is it possible to solo mine?

**Comment by andru-kun** [comment]
no, wildrig doesn't support solo mining to a node/etc.

**Comment by nessuz** [comment]
So this won't work? 

wildrig.exe -a nexapow  -o stratum+tcp://stratum-eu.rplant.xyz:7092 -u wallet -p m=solo

**Comment by andru-kun** [comment]
man, this is a question about pool, I can't predict your thoughts :) And that will work, yes

**Comment by nessuz** [comment]
I figured :) thanks bro!
