### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by luc1an24** [andru-kun/wildrig-multi#21]
Hi
Thank you for your help all requests.
The latest addition `--benchmark-timeout` could have some improvements though.
Is there a way that you could output avg. hashrate at the end of Benchmark?
Like so: `Benchmark finished: Avg. hashrate is 15 kh/s` or something in this style.

This would help us to get more precise statistics since 10s/60s/15m and max speeds are good for mining but not for benchmarking which takes more than 10 and sometimes less then 60 s, giving us bad results.

Btw: wildrig-multi is already listed as external plugin on NiceHash! :)

Also are there any system environment variables that should be set while running your program?

**Comment by andru-kun** [comment]
sounds like a good idea :) So will check what can I do when I get some free time.

**Comment by UselessGuru** [comment]
> no need to change system defaults if they wasn't changed

What are the defaults you expect?

**Comment by andru-kun** [comment]
> What are the defaults you expect?

Just no GPU_* environment variables in system :)

**Comment by luc1an24** [comment]
It would be great if you could do that. I will be off for a week or two now so you have some time ;)

**Comment by andru-kun** [comment]
> 
> 
> It would be great if you could do that. I will be off for a week or two now so you have some time ;)

Just want to say that I still remember about this request, but not implemented it yet in latest previews because of Navi support and not much free time. Probably will implement next week.

**Comment by andru-kun** [comment]
Closing as very old and changed NiceHash politics about 3rd party miners )
