### ISSUE TITLE
failed to allocate memory for precompute buffer

### ISSUE THREAD

**Issue by t8kinover** [andru-kun/wildrig-multi#213]
After increasing virtual memory I get this error on wildrig version 36.2 & .3. Using Windows 10 21h2 19044.2251
![image](https://user-images.githubusercontent.com/57022843/213210327-69a4fa6b-5b24-473a-861e-312c40e4edfe.png)

**Comment by andru-kun** [comment]
> Yes I was not sure what to set the initial size to.. it is currently at 6000 mb. I did try it set at 9000 with no luck. The maximum size is currently 9050

I think you allocate only 9000Mb? You should allocate 9000 per GPU. So in your case it's 36000MB. Or how many GPU's you have?

**Comment by t8kinover** [comment]
Fixed, Thank you.
