### ISSUE TITLE
Error CL_BUILD_PROGRAM_FAILURE

### ISSUE THREAD

**Issue by Domonotor** [andru-kun/wildrig-multi#214]
I am new to mining so I apologise if I am missing something obvious or don't understand.
I am having the following issue when mining Nexa.
I have tried a slew of other previous issue fixes and nothing seems to have done it. Would anyone know what my issue is?

![image](https://user-images.githubusercontent.com/123201099/213779956-1f04e6ee-8b06-4860-8701-051315505944.png)

**Comment by andru-kun** [comment]
Right now RDNA3 is broken, try version 0.36.1 In next release it will be fixed
