### ISSUE TITLE
Memory access fault by GPU node-1

### ISSUE THREAD

**Issue by calipomza** [andru-kun/wildrig-multi#217]
The miner show  "Memory access fault by GPU node-1 (Agent handle: 0x5555570f0520) on address 0x6590c6c73000. Reason: Page not present or supervisor privilege" in my rig with 9 6600 non xt.Anyidea?

**Comment by andru-kun** [comment]
Reduce your OC, or increase core voltage a bit. Gpu just crashes

**Comment by calipomza** [comment]
Reduce OC will be reduce core?

**Comment by calipomza** [comment]
Thanks

**Comment by calipomza** [comment]
Works fine.... Thanks
