### ISSUE TITLE
Rx 6950 xt not works ?

### ISSUE THREAD

**Issue by Anthony-landry** [andru-kun/wildrig-multi#221]
hello, 

I have tested the latest version of wildRig on HiveOS with cma Rx 6950 XT and it does not work,

in the specs it says this : DNA 2nd gen: Radeon 6500XT, Radeon 6600XT, Radeon 6700 XT, Radeon 6800XT, Radeon 6900 XT

but on hashrate.no it says that the rx 6950 xt works with Nexa mining.

thanks in advance

Best regards

**Comment by andru-kun** [comment]
it does work. probably you set wrong settings in your Flight Sheet. Most common problem - use pool for nexa from HiveOS list, they messed up it. Set pool url in miner config instead of list

**Comment by Anthony-landry** [comment]
I have just re-tested and it now works on the rx6950xt 

I haven't touched any of the settings or configurations ... 

thanks for everything
