### ISSUE TITLE
Windows difficulty not working - BTRM

### ISSUE THREAD

**Issue by LADGRES** [andru-kun/wildrig-multi#237]
Using Wildrig to mine BTRM on Vipor. I have multiple rigs set up in HiveOS.  To set difficulty on vipor, they use the password field (ie. d=0.5 in the password field) and it works fine through HiveOs.  

However, when I try to set it up on a Win 10 computer (-p d=0.5), it looks like it sets correctly on the pool side but for some reason the miner starts showing errors "low difficulty share - share rejected" errors. 

It does work perfectly if you don't set a difficulty (defaults to variable difficulty on pool)

Is there something that I am doing wrong when formatting the command?  I have tried with/without quotes, brackets, etc ... same result.

Thanks for any help!

![wildrig-error](https://user-images.githubusercontent.com/34575214/233735418-076a7a8a-8877-4798-8dc9-4cdcd4ff9f65.jpg)

**Comment by andru-kun** [comment]
Problem is pool changes the difficulty right after the new job(you can see the message "Stratum set raw difficulty"), and miner don't like that. Will try to fix this in future releases.

**Comment by andru-kun** [comment]
should be fixed in 0.39.6
