### ISSUE TITLE
At Random Crashing

### ISSUE THREAD

**Issue by RGlabs84** [andru-kun/wildrig-multi#24]
I personally love this miner, the algo support list is huge, and it does mine great, when it works.  Since version 0.17.2 and up and single vega56 card randomly hard lock crashes when using wildrig, doesnt matter what im mining, sometimes if im lucky the watchdog catches it, but will hard crash when exiting wildrig instead.  I wish i had more reason to why, but im not getting an actual error code, the worst part is the total randomness,
sometimes ill have 3-5days of up time without issues, other time 5-10, even 20 minutes..

I do not have this issue with any other miner..the problem is i want to use your miner, but reliability..

Anything information i can provide to help determine root cause im all for sending over.  I am using newest amd driver, 19.9.2, newest windows 10, all updated blah blah blah, even at stock clock/volt settings...so its not an oc issues

**Comment by RGlabs84** [comment]
Feel free to request any documents that could help

**Comment by RGlabs84** [comment]
okay, so i now have some other AMD cards in my jiffy rig, the only time the miner crashes is when using the Vega on Wildrig, 4 rx550s mine fine, the minute the vega56 comes it, ill get at random crashes, not just gpu hang and quit errors, sometimes hard locks.  

i have since updated to the newest version 19.1 of wildrig, same issue, i can mine everything fine until the vega comes into play. its rock solid elsewhere..but i need the algo support of this miner, and the performance of this miner is off the charts.  PLEASE HELP!

**Comment by andru-kun** [comment]
Hi, unfortunately have no idea what can be wrong. This can be PSU problem or just gpu itself. Since version 0.17.2 there was some kernel improvements, so maybe that increased gpu utilization and as a result - higher requirements for gpu/psu stability.

One idea I have - can you mine on Vega using separate instance of miner(running with parameter --multiple-instance) and another one for 4xRX550?

**Comment by RGlabs84** [comment]
I will give it a try. It seems to only affect the Vega, the RX group never
dies.

**Comment by RGlabs84** [comment]
so far so good, i also want you to know that, i disabled multiple gpus before even originally posting, i even put the system down to 1 vega and 2 rx550s, i can tell you right now that multi instance has created a weird load on the vega, which hwinfo show it now hitting my core clocks, but at a very reduced draw
