### ISSUE TITLE
Error CL_INVALID_WORK_GROUP_SIZE when calling clEnqueueNDRangeKernel for kernel 'cn1'

### ISSUE THREAD

**Issue by DeLaguna** [andru-kun/wildrig-multi#240]
Command line being used

--algo ghostrider --opencl-threads auto --url (POOL:RTM-SUPRNOVA-LA)⁣⁣⁣ --user (WALLET:SUPERNOVAUSERNAME)⁣⁣⁣.(WORKER)⁣⁣⁣-GPU --pass n=XXXX

**My Rig**
Overview
Computer model: MiniBeast (TheRealSarcasmO)
Operating system: Microsoft Windows 11 Pro (10.0, Build 22621)
Processor: AMD Ryzen 9 7950X 16-Core Processor             16/32
Motherboard: ASUSTeK COMPUTER INC. ROG STRIX X670E-I GAMING WIFI
RAM: 64 GB
Hard disk1: Samsung SSD 980 PRO 2TB (1.8 TB/Fixed hard disk media)
Hard disk2: Generic MassStorageClass USB Device (0.0 bytes/)
Hard disk3: ROG ESD-S1C SCSI Disk Device (1.8 TB/External hard disk media)
Hard disk4: Generic MassStorageClass USB Device (0.0 bytes/)
Hard disk5: WD_BLACK SN770 2TB (1.8 TB/Fixed hard disk media)
Hard disk6: USB DISK 3.0 USB Device (14.4 GB/Removable Media)
Graphics card1: AMD Radeon RX 7900 XT (20.0 GB)
Graphics card2: AMD Radeon(TM) Graphics (512 MB)
Monitor1: AVX AVT GC553 (1920x1080 / 15.3 Inch)
Monitor2: Samsung SAMSUNG (1920x1080 / 50.1 Inch)
Sound card1: Advanced Micro Devices AMD High Definition Audio Device
Sound card2: Advanced Micro Devices AMD High Definition Audio Device
Sound card3: (Generic USB Audio) USB Audio Device
Sound card4: AMD Streaming Audio Device
Sound card5: SteelSeries ApS SteelSeries Sonar Virtual Audio Device
Sound card6: Razer Inc Razer Kiyo
Keyboard: ROG CLAYMORE II
Mice1: HID-compliant mouse
Mice2: HID-compliant mouse
Audio1: Microsoft Streaming Service Proxy
Audio2: AMD High Definition Audio Device
Audio3: Florentino's Z Fold4 Hands-Free HF Audio
Audio4: AMD High Definition Audio Device
Audio5: Live Gamer Ultra-Audio
Audio6: AMD Streaming Audio Device
Audio7: Florentino's Z Fold4 A2DP SNK
Audio8: SteelSeries Sonar Virtual Audio Device
Camera: Live Gamer Ultra-Video

**Comment by ahorek** [comment]
+1 same issue https://discord.com/channels/484987277596950538/484987277596950540/1077658843967922216

**Comment by ahorek** [comment]
fixed in 0.36.7
