### ISSUE TITLE
v0.36.10 (Windows): Error nexapow@nicehash

### ISSUE THREAD

**Issue by UselessGuru** [andru-kun/wildrig-multi#243]
`Bin\Wildrig-v0.36.10\wildrig.exe --algo nexapow --api-port 4001 --url stratum+tcp://nexapow.auto.nicehash.com:9200 --user ##############################.############ --pass x --multiple-instance --opencl-platforms 1 --opencl-devices 1`

No error message, nothing. Miner just exits.
Same with all 3 GPUS tested (GTX 1660 Super, RX580 & RX5700)

```
 ###################################
 #################  ################
 ################    ############### * ABOUT:    WildRig/0.36.10 beta libuv/1.21.0
 ####   #########    #########   ### * CPU:      Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
 ####     #######    #######     ### * ALGO:     nexapow
 ####   #  ######    ######      ### * POOL #1:  nexapow.auto.nicehash.com:9200
 ####   ##  #####    #####  ##   ### * API PORT: 4001
 ####   ##   #####  #####   ##   ### * COMMANDS: hashrate, statistics
 ####   ##   #####  #####  ###   ###
 ####   ###  #####  #####  ###   ###   devfee: 2%
 ####   ###  ####    ####  ###   ###   send-stale: no
 ####   ###   ###    ###   ###   ###   watchdog: disabled
 ####   ##    ##      ##    ##   ###
 ####      #####  ##  #####      ###
 ####   #   ###  ####  ###   #   ###
 ####   ##       ####       ##   ###
 ####   #####  #      #  #####   ###
 ####   #####  ###  ###  #####   ###
 ####                            ###
 ############   ##  ##   ###########
 #############   #  #   ############
  #############        #############
      ###########    ###########
          ##################

[09:03:16] initializing GPUs...
[09:03:16] GPU #1: AMD Radeon RX 5700 XT [busID: 9] [arch: gfx1010]
[09:03:16] threads: 1, intensity: 22, worksize: 0/256, cu: 40, mem: 8176Mb

C:\>
```

**Comment by UselessGuru** [comment]
Seems to be a pool problem - nexapow@zergpool is working

**Comment by andru-kun** [comment]
yeah, I don't support nicehash variant of protocol with different extra nonce size and probably won't fix that, because no sense )

**Comment by UselessGuru** [comment]
> I don't support nicehash variant of protocol 
Thank you for the response.
Is this true only for nexapow or what other algos are also not supported @nicehash?

**Comment by andru-kun** [comment]
> Is this true only for nexapow or what other algos are also not supported @nicehash?
As I remember yes, all other algorithms(on nicehash supported by wildrig) use not modified protocol so it should work.
