### ISSUE TITLE
RTX 3060 & RTX 3060 ti mining ghostrider algo

### ISSUE THREAD

**Issue by andreiotetea** [andru-kun/wildrig-multi#244]
Hello, I have a lot of rejected shares mining this, I tried to change clocks but is no difference, if I mine other coin on the same pool is no rejected shares. pool is rplant, I tried to change the pool thinking of connection time... to something closer and even so...still get same 20-25% rejected shares. If you can fix this...thanks!
![testmining](https://github.com/andru-kun/wildrig-multi/assets/6104936/874c669f-cfc3-4e1f-9fff-ba79cf1a6289)

**Comment by andreiotetea** [comment]
> Hello, I have a lot of rejected shares mining this, I tried to change clocks but is no difference, if I mine other coin on the same pool is no rejected shares. pool is rplant, I tried to change the pool thinking of connection time... to something closer and even so...still get same 20-25% rejected shares. If you can fix this...thanks! ![testmining](https://user-images.githubusercontent.com/6104936/265245815-874c669f-cfc3-4e1f-9fff-ba79cf1a6289.png)

In picture y see less rejected because I restarted...and in time is going to 20-25%...

**Comment by andru-kun** [comment]
try additional parameter ``--opencl-launch 1024``

**Comment by andreiotetea** [comment]
> try additional parameter `--opencl-launch 1024` Later I will try to check what's wrong with this algo on those cards

thanks, I will give a try and let y know if still problem

**Comment by andreiotetea** [comment]
> > try additional parameter `--opencl-launch 1024` Later I will try to check what's wrong with this algo on those cards
> 
> thanks, I will give a try and let y know if still problem

I tested and is way more better than before, look:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫Statistics┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ID Name                         Hashrate Temp  Fan  Pwr   Eff CClk MClk     A   R   I
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 #0 GeForce RTX 3060 Ti          1553 H/s  65C  76%  97W 16.01 1650 7800   106   2   -
 #1 GeForce RTX 3060 Ti          1535 H/s  58C  76% 100W 15.35 1650 7800    98   1   -
 #2 GeForce RTX 3060 Ti          1476 H/s  66C  78%  88W 16.78 1455 7800   126   -   -
 #3 GeForce RTX 3060             1293 H/s  60C  86%  88W 14.69 1650 8305    92   2   -
 #4 GeForce RTX 3060 Ti          1534 H/s  61C  72% 103W 14.90 1650 7800   126   1   -
 #5 GeForce RTX 3060 Ti          1555 H/s  60C  87% 105W 14.81 1650 7800   111   2   -
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 10s:                            8948 H/s Power:    581W            Accepted:      659
 60s:                            8560 H/s                           Rejected:        8
 15m:                            8164 H/s                           Ignored:         -
┫0 days 03:19:06┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

**Comment by Alirezazaktab110** [comment]
> try additional parameter `--opencl-launch 1024` Later I will try to check what's wrong with this algo on those cards

hi bro, I have this issue on my rig too. I run 3070 rog and 3070 plait gamerock with many different OCs but there are many rejected shares. with command --opencl-launch 1024 it becomes much better for me thanks

algo:                       ghostrider 
my pool:                 rplant
os:                           win 11 pro 64-bit 21H2
display settings:     1440p @100Hz

and please add algo+zil thanks alot

**Comment by andru-kun** [comment]
should be fixed in newer versions



> and please add algo+zil thanks alot

working on that
