### ISSUE TITLE
RTX 3070 (Reaction, ghostrider algo) hashrate jumps from 1.2 k/h to 2.6 k/h 

### ISSUE THREAD

**Issue by ANoff123** [andru-kun/wildrig-multi#246]
Hello,
RTX 3070 (Reaction coin, ghostrider algo). Hashrate is not stable. It jumps drammaticly up and down from 1.2 k/h to 2.6 k/h and back 
My settings: Cclk 1710, Mclk 6800, Pl 120
The same issue on 0.36.7, 0.36.8, 0.36.10 version.
Is this normal?  

![Reaction hashrate](https://github.com/andru-kun/wildrig-multi/assets/126074588/1fa530df-7cd5-4b7c-a666-e970fd4ab20d)
![Reaction hashrate 2 1 kh](https://github.com/andru-kun/wildrig-multi/assets/126074588/9ae51c4e-3574-434f-9c57-708c207ff72a)
![Reaction hashrate 1 2 kh](https://github.com/andru-kun/wildrig-multi/assets/126074588/6615aa59-45c4-4d90-98ad-7abde1f72453)

**Comment by andru-kun** [comment]
Hi, this is how algorithm works. As you can see, there is hashorder thing below new job messages. Every new block changes it, and depends on it hashrate will jump higher or fall down. Most impact is from red CN hashfuncs.

**Comment by qiukeln** [comment]
> Hi, this is how algorithm works. As you can see, there is hashorder thing below new job messages. Every new block changes it, and depends on it hashrate will jump higher or fall down. Most impact is from red CN hashfuncs.

Hi brother. May I ask if vega56 is suitable for mining this coin?

**Comment by andru-kun** [comment]
> > Hi, this is how algorithm works. As you can see, there is hashorder thing below new job messages. Every new block changes it, and depends on it hashrate will jump higher or fall down. Most impact is from red CN hashfuncs.
> 
> Hi brother. May I ask if vega56 is suitable for mining this coin?

yes, Vega cards should be good here. The only problem - you need old drivers for them
