### ISSUE TITLE
--proxy can not be used

### ISSUE THREAD

**Issue by tiantangge** [andru-kun/wildrig-multi#247]
0.36.7-0.36.10 --proxy #symbol appeared in the kernel，So it cannot be used，0.36.6beta is ok，this is bug, please repair as soon as possible
The format is wrong and cannot be connected
![266312645-109f60aa-7dc1-4e54-b43a-88d35163aac7](https://github.com/andru-kun/wildrig-multi/assets/144345073/c8ad3624-d615-4718-af35-5de879f000d9)

**Comment by andru-kun** [comment]
Can you share your bat file? Or full string of --proxy parameter?

**Comment by tiantangge** [comment]
> Can you share your bat file? Or full string of --proxy parameter?

--proxy 192.168.8.1:1070 --opencl-launch 2560

**Comment by tiantangge** [comment]
> Can you share your bat file? Or full string of --proxy parameter?

The same --proxy parameter is updated 0.36.7-0.36.10 and cannot be used.

**Comment by andru-kun** [comment]
ok, I will check that, probably broke parsing when added user and password support for proxy. Can you try --proxy socks5://192.168.8.1:1070 ?

**Comment by tiantangge** [comment]
> ok, I will check that, probably broke parsing when added user and password support for proxy. Can you try --proxy socks5://192.168.8.1:1070 ?
Try the result and the same as --Proxy 192.168.8.1:1070, the proxy format in the kernel is not right

**Comment by andru-kun** [comment]
Hmm, checked everything and it works fine. What you see is only visual glitch, I will fix that later.
