### ISSUE TITLE
curvehash problem!

### ISSUE THREAD

**Issue by MTCHANNELL** [andru-kun/wildrig-multi#249]
Hello. I want to consult on something. I want to mine the coin "Pulsarcoin-curvehash". However, I am faced with an interesting situation. When I try with "Srbminer", the computer reboots itself after receiving 4-5 "acceptances". If I try with "Wildrig" it doesn't accept any jobs. However, when I try with "wildrig" the computer does not restart. He just doesn't accept jobs.
Methods I tried;
1-) I formatted and reinstalled Windows (not solved)
2-) I tried the oldest driver and the newest drivers (didn't solve)
3-) I tried various Linux systems (not solved)
4-) I tried formatting Win10-11 (it didn't solve)
I have no problems other than the Curvehash algorithm. Currently I want to mine "pulsarcoin" with my processors and graphics cards. There is no problem on the processor side. (MinotaurX). But unfortunately, no matter what I did on the graphics card side, I could not solve the problem.
srbminer command line: SRBMiner-MULTI.exe --disable-cpu -a curvehash -o pool -u wallet -p x
wildrig command line: wildrig.exe -a curvehash -o pool -u wallet -p x
GPUs: Rx570 8Gb 256Bit
I would be very happy if you could help me in your free time.

**Comment by andru-kun** [comment]
Hi, try latest version - 0.36.10. Or better try 0.34.0 where nexapow is not implemented yet and curvehash was working fine on old Polaris gpu's

**Comment by MTCHANNELL** [comment]
Even though I tried old versions before, they did not work. but it works now. I think he was waiting for you to help :) thank you for everything.
solution : wildrig 0.34.0
