### ISSUE TITLE
Poorer efficiency with newer version 0.38.0 by mining Skydoge

### ISSUE THREAD

**Issue by UHeinz13** [andru-kun/wildrig-multi#254]
In version 0.38.0, I can set a maximum of 2 threads, which leads to poorer efficiency for me!
With the previous version 0.37.2 I could set more threads, in my case 4 threads, for a 5 percent better efficiency for mining Skydoge! Is it possible to change this in a new version? Please. At the moment i use veriion 0.37.2 with the entry opencl-launch 17x32 --opencl-threads 4 for the best efficiency 0.24 at my RTX 4060TI! with the new one its only 0.225.

**Comment by andru-kun** [comment]
Higher than 2 threads per gpu can lead to incorrect hashrate calculations, so I'm not sure that efficiency you get is real.

**Comment by UHeinz13** [comment]
Okay, of course that could be the case. But I have now found a solution. I have changed the settings: Core 2190 Mem 5000, Coreoffset 0, --opencl-launch 17x32 --opencl-threads 2. I now have an efficiency of 0.243 again, so this error can be closed. Thanks again!
