### ISSUE TITLE
Cant connect to ta devfee pool and stopped mining 

### ISSUE THREAD

**Issue by drdynamicg** [andru-kun/wildrig-multi#257]
![image](https://github.com/andru-kun/wildrig-multi/assets/150393087/4efc6937-e496-4f0f-85ab-f9f336e7ba1a)

**Comment by andru-kun** [comment]
Where are you from, China?

**Comment by drdynamicg** [comment]
india

**Comment by andru-kun** [comment]
> india
Ok, I will try to add more devfee pools nearby to next release to fix this problem

**Comment by drdynamicg** [comment]
Thanks a lot.  , Don't you have Discord server, If not plzz make it , for
community

**Comment by andru-kun** [comment]
I have
https://discord.gg/9pR7WMkt

**Comment by andru-kun** [comment]
try version 0.38.3
