### ISSUE TITLE
pdn pufferfish dev fee / mining causes crash - no pool

### ISSUE THREAD

**Issue by mahalamobile** [andru-kun/wildrig-multi#258]
so the only pool for pdn is panadanite.work, so when the dev fee kicks in think it tries to mine somewhere else and the pool doesnt exists and it crashes (hiveos). had to revert back to 36.10 which is only prior version that works now on pandanite. please fix and release in next version :)

**Comment by andru-kun** [comment]
coin is dead right, so I can't fix this )

**Comment by andru-kun** [comment]
ok, looks like found why it still crashes

**Comment by hellegaard1** [comment]
came to start open another issue about rtm on ghostrider. Connecting through with no tls, connection reset by peer. Vpn without tls works fine, but running tls makes dev fee not work right at all. Everything after 36.10 this happens to.

**Comment by andru-kun** [comment]
> came to start open another issue about rtm on ghostrider. Connecting through with no tls, connection reset by peer. Vpn without tls works fine, but running tls makes dev fee not work right at all. Everything after 36.10 this happens to.

problem is old versions just trying all dev-fee time to connect and do nothing if fail, new versions just stop mining. Crash happens because of some bug when too many tries to re-connect.

**Comment by hellegaard1** [comment]
> 
> problem is old versions just trying all dev-fee time to connect and do nothing if fail, new versions just stop mining. Crash happens because of some bug when too many tries to re-connect.

Fix in progress then?

**Comment by andru-kun** [comment]
> > problem is old versions just trying all dev-fee time to connect and do nothing if fail, new versions just stop mining. Crash happens because of some bug when too many tries to re-connect.
> 
> Fix in progress then?

Well, I will try to fix crash, but nothing I can do with connection to a dev-fee if some vpn's and so on are used, that are blocking it :)

**Comment by hellegaard1** [comment]
> 
> Well, I will try to fix crash, but nothing I can do with connection to a dev-fee if some vpn's and so on are used, that are blocking it :)

No worries, didn't expect it. I've just only been able to use a vpn to bypass the dev fee issue as using no vpn on non tls port gives a "connection reset by peer", and the tls port just completely breaks the dev fee for some reason. Vpn & no tls works for me until a fix gets released.

**Comment by mahalamobile** [comment]
what u mean coin is dead, i run a pool at pandanite.work and have 30 miners mining it currently. please can you look to fix the dev fee problem as guys want to use wildrig multi for pufferfish but its crashing on the newer versions, all the way back to 36.10 is ok then after that it breaks. many thanks

**Comment by andru-kun** [comment]
> what u mean coin is dead, i run a pool at pandanite.work and have 30 miners mining it currently. please can you look to fix the dev fee problem as guys want to use wildrig multi for pufferfish but its crashing on the newer versions, all the way back to 36.10 is ok then after that it breaks. many thanks

Ok, coin is frozen, read official announcement:
_Mining towards any other pool/nodes will not carry over balances to new forked project, as ledger that is saved in current state will be taken from the current height that was achieved: 637437_

**Comment by mahalamobile** [comment]
yes that announcement was from one of the pool operators, remember a
blockchain cant be owned otherwise defeats the purpose doesnt it. i still
run the pool, the blockchain is alive, if others want to fork then they can
lol

regards,

**Comment by andru-kun** [comment]
Well, probably I will just remove this algo from the list. I didn't sell any of my PDN's, and now I can't, same story was with Ring coin. It was fun to implement pufferfish2, but now I don't see any reason to continue support it, no more fun and no profit => no sense

**Comment by mahalamobile** [comment]
Hold on. Code base is being rewritten. Don't burn ur coins just yet.
Project still going ;)
