### ISSUE TITLE
CPU 100% on Ghostrider

### ISSUE THREAD

**Issue by megalolka** [andru-kun/wildrig-multi#264]
Hi! A new version of WRM published yesterday (0.39.5) has a 100% CPU load on Ghostrider

**Comment by andru-kun** [comment]
Ok, bug confirmed, it appears only on Windows. Fix will be in next release

**Comment by mralemao** [comment]
on my Windows OS there was also a problem with the CPU. thanks.

**Comment by girafa900** [comment]
Add in the next version to display in each table the coin that is being mined. For example, the Ghostrider algorithm. And there are a lot of coins. It is difficult to understand which one is being mined.

**Comment by andru-kun** [comment]
should be fixed in 0.39.6
