### ISSUE TITLE
0.39.7 (Windows): x21s not working with Nvidia GTX 750 or GT 1030

### ISSUE THREAD

**Issue by UselessGuru** [andru-kun/wildrig-multi#268]
`\Wildrig-v0.39.7\wildrig.exe --algo x21s --watchdog --api-port 4004 --url stratum+tcp://x21s.eu.mine.zergpool.com:3224 --user *********************** ***--pass c=BTC,ID=************ --multiple-instance --opencl-platforms 1 --opencl-devices 2`

```
 ###################################
 #################  ################
 ################    ############### * ABOUT:    WildRig/0.39.7
 ####   #########    #########   ### * CPU:      Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
 ####     #######    #######     ### * ALGO:     x21s
 ####   #  ######    ######      ### * POOL #1:  x21s.eu.mine.zergpool.com:3224
 ####   ##  #####    #####  ##   ### * API PORT: 4004
 ####   ##   #####  #####   ##   ### * COMMANDS: hashrate, statistics
 ####   ##   #####  #####  ###   ###
 ####   ###  #####  #####  ###   ###   devfee: 0.75%
 ####   ###  ####    ####  ###   ###   send-stale: no
 ####   ###   ###    ###   ###   ###   watchdog: enabled
 ####   ##    ##      ##    ##   ###
 ####      #####  ##  #####      ###
 ####   #   ###  ####  ###   #   ###
 ####   ##       ####       ##   ###
 ####   #####  #      #  #####   ###
 ####   #####  ###  ###  #####   ###
 ####                            ###
 ############   ##  ##   ###########
 #############   #  #   ############
  #############        #############
      ###########    ###########
          ##################

```
[23:17:19] initializing GPUs...
[23:17:19] PTX ISA: 8.3
[23:17:19] GPU #2: NVIDIA GeForce GTX 750 Ti [busID: 16] [arch: sm50]
[23:17:19] threads: 1, intensity: 19, worksize: 256/1024, cu: 5, mem: 2047Mb
[23:17:19] Error CL_INVALID_BINARY when calling clBuildProgram for lyra441p2
[23:17:20] Error CL_INVALID_BINARY when calling clBuildProgram for lyra441p2_mod
[23:17:21] Error CL_INVALID_PROGRAM when calling clCreateKernel for kernel 'lyra441p2'
[23:17:22] Failed to start OpenCL threads

Edit: Same error with GT1030

**Comment by andru-kun** [comment]
should be fixed in 0.39.8
