### ISSUE TITLE
0.39.9 (windows): API not working???

### ISSUE THREAD

**Issue by UselessGuru** [andru-kun/wildrig-multi#271]
`Wildrig-v0.39.9\wildrig.exe --algo ghostrider --watchdog --api-port 4003 --url stratum+tcp://stratum1.hashcryptos.com:9997 --user **************** --pass x --multiple-instance --opencl-platforms 0 --opencl-devices 2`

No response on http://127.0.0.1:4003

**Comment by andru-kun** [comment]
interesting, what if try http://localhost:4003? I have changed the lib, so that might be the case

**Comment by andru-kun** [comment]
so yes, it's completely broken, not enough tests done, thought it will bind everything automatically... %) Need to list all IP addresses manually, will fix in 0.39.9a

**Comment by UselessGuru** [comment]
See https://github.com/andru-kun/wildrig-multi/issues/272
