### ISSUE TITLE
0.39.9a: API has changed

### ISSUE THREAD

**Issue by UselessGuru** [andru-kun/wildrig-multi#272]
`http://127.0.0.1:nnnn/api.json` is no longer working.

However I can get a response on 

`http://127.0.0.1:nnnn`

Is this change intentional? It breaks XmRig API compatibility.

**Comment by andru-kun** [comment]
Looks like old solution was redirecting everything to root, new one is not and that was not intentional, I just missed this thing because of using root all the time for my tests

**Comment by andru-kun** [comment]
I can return that, but don't know when new release will be ready

**Comment by UselessGuru** [comment]
> I can return that, but don't know when new release will be ready

For me this is not a biggie - I've already created a nei API file.
But I am not sure about other integrations (Rainbow miner, HiveOs etc.)

**Comment by andru-kun** [comment]
> > I can return that, but don't know when new release will be ready
> 
> For me this is not a biggie - I've already created a nei API file. But I am not sure about other integrations (Rainbow miner, HiveOs etc.)

yeah, some software probably will break, it's still a surprise for me why some did use /api.json ) Damn, probably need to release 0.39.9b xD
