### ISSUE TITLE
Dropped Hashrate on Rx570, 580, 590 mining Skydoge

### ISSUE THREAD

**Issue by Blackbunny76** [andru-kun/wildrig-multi#279]
In last versions hashrate drop, Varies from 7.x to 5.x
In 39b sometimes rx590 has 7.2 others 5.6 and in this 39b and 39c rx570 drop from 6.5 to 5.7 in 9 of 10 times
I go back to 39b because 39c is more inestable and has more low hashrate in skydoge

**Comment by andru-kun** [comment]
There was no changes in 0.39.9c for mining at all, so search reason in clocks, connection stability and so on
