### ISSUE TITLE
Problem with memory clock

### ISSUE THREAD

**Issue by fabiowa15** [andru-kun/wildrig-multi#280]
It is not possible to set the memory clock, even using the --gpu-memory-clock or --mclk commands; the clock is not set. I am running the miner on Windows.

My GPU cards are: RTX 3060 TI and RTX 3070.

**Comment by andru-kun** [comment]
you need to run miner with admin rights(check **start-Radiant_lockMemory.bat** to see how to do it properly). Also you need properly installed drivers. If miner shows red label err instead of clocks/temperature/etc. when you press h - uninstall drivers with DDU tool, disable Windows driver installation(check settings of that app) and install official NVIDIA drivers.

**Comment by fabiowa15** [comment]
I'm already running as an administrator. Furthermore, the drivers are all up to date.

**Comment by andru-kun** [comment]
> I'm already running as an administrator. Furthermore, the drivers are all up to date.

and miner do show you statistics with temperature and clocks without issue?

**Comment by fabiowa15** [comment]
> > I'm already running as an administrator. Furthermore, the drivers are all up to date.
> 
> and miner do show you statistics with temperature and clocks without issue?

Yes. Image attached. Memory clock setted to 1000 and running at 5000.

![Sem título](https://github.com/andru-kun/wildrig-multi/assets/152726294/7c6dcdb8-3b7d-483e-a2bf-3fac4bb155b1)

**Comment by andru-kun** [comment]
you can't lock memory at 1000, possible value is 810. If you want to OC memory and add +1000 use --gpu-memory-offset for that

**Comment by andru-kun** [comment]
no, it doesn't work like that :) You can add/substract value from stock memory clock using --gpu-memory-offset or lock memory to a specific value using --gpu-memory-clock

**Comment by fabiowa15** [comment]
> não, não funciona assim :) Você pode adicionar/subtrair valor do relógio de memória padrão usando --gpu-memory-offset ou bloquear a memória para um valor específico usando --gpu-memory-clock (as variantes são limitadas aqui, depende do GPU)

I understand. If the memory clock variants are limited, I will never be able to set it to the value I want, for example, 1000.

Thanks.
:)
