### ISSUE TITLE
Upgraded from V0.40.0A to V 40.1 - Skydoge Decreased Performance

### ISSUE THREAD

**Issue by lightningfrost** [andru-kun/wildrig-multi#281]
Upgraded from V0.40.0A to V 40.1 - Skydoge Decreased Performance - Running an Nvidia RTX 4090.  Hashrate went from around 80mh to 55mh, Watts went from 444w to 410w, and temp went from 80 to 73c.

**Comment by andru-kun** [comment]
yeah, regression confirmed, will fix in next release. Looks like only RTX 3000 series benefit from optimizations

**Comment by andru-kun** [comment]
0.40.1a should fix the issue
