### ISSUE TITLE
Intel GPU A770 no start mining

### ISSUE THREAD

**Issue by matcin1234** [andru-kun/wildrig-multi#285]
Hi, miner not starting on Intel A770 GPU. Latest drivers installed. Does anyone have an idea why I can't see the card on miner?
![Wildrig](https://github.com/andru-kun/wildrig-multi/assets/79340965/f9eb01cd-c1c0-437c-99ed-14098518a61c)

**Comment by andru-kun** [comment]
what OS is that? What command line do you use?

**Comment by matcin1234** [comment]
I use win 10 pro 22H2.

@echo off

:loop
WildRig --algo kawpow --url stratum+tcp://clore.2miners.com:2020 --user **************************************** --pass x


if ERRORLEVEL 1 goto custom
timeout /t 5
goto loop

:custom
echo Custom command here
timeout /t 5
goto loop

**Comment by andru-kun** [comment]
> I use win 10 pro 22H2.
> 
> @echo off
> 
> :loop WildRig --algo kawpow --url stratum+tcp://clore.2miners.com:2020 --user **************************************** --pass x
> 
> if ERRORLEVEL 1 goto custom timeout /t 5 goto loop
> 
> :custom echo Custom command here timeout /t 5 goto loop

something definitely not good with drivers, what exact version did you install? Any screen from Intel Arc Control? Also is it just one card?

**Comment by matcin1234** [comment]
only one card.
![Arc](https://github.com/andru-kun/wildrig-multi/assets/79340965/979b3be6-b0ec-454c-b88d-47bae9219f59)

**Comment by andru-kun** [comment]
Can you run TechPowerUP GPU-Z? Is there OpenCL available? Or you get something like this?
![Rhysepewpew_0-1673735304441](https://github.com/andru-kun/wildrig-multi/assets/16541824/ca75c94b-5b18-4935-8042-42cd8e7d70c9)

**Comment by matcin1234** [comment]
I have it exactly like this
![gpuz](https://github.com/andru-kun/wildrig-multi/assets/79340965/921cab26-f662-444f-9d82-19cc6b6fdd3f)

**Comment by andru-kun** [comment]
> I have it exactly like this

so yeah, something is wrong with drivers. Can you uninstall them with [Display Driver Uninstaller](https://www.guru3d.com/download/display-driver-uninstaller-download/) tool and install [latest WHQL certified version(31.0.101.5122)](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html)?

**Comment by andru-kun** [comment]
A bit later I will try one thing on my side and prepare a beta version for you if you don't mind

**Comment by matcin1234** [comment]
It helped DDU, thank you very much for your help!
Ok.

**Comment by matcin1234** [comment]
Do you have a setup for kawpow clore  for A770? I get only 25mh/s..

**Comment by andru-kun** [comment]
> Do you have a setup for kawpow clore for A770? I get only 25mh/s..

Unfortunately I don't, also not much you can do with it on Windows. [Hashrate.no](https://hashrate.no/gpus/a770/CLORE) did use mmpOS for testing, probably there it's possible to lock core clock at 2350 for a result 32MH/s

**Comment by Customayzer** [comment]
I was unable to reach 32 m/h in mmpos with your miner. I thought maybe this is possible on a 16 GB card, but I have 8. Who knows? When I set the power limits to 168 and the core to 2350, the core was approximately 2100-2150. But I liked the miner itself)

**Comment by Customayzer** [comment]
The coolers are also not adjustable in mmpos a770 and spin at basic speeds and at kawpow it is very hot. Maybe you can increase the speed of coolers for intel arc in the miner settings? If so, how?

**Comment by andru-kun** [comment]
> I was unable to reach 32 m/h in mmpos with your miner.

definitely need to ask r0ver2 how he did that )

> Maybe you can increase the speed of coolers for intel arc in the miner settings? If so, how?

Unfortunately I can't, Intel provided library for monitoring and some other staff only for Windows, but even there it sucks. How to control something on Linux, or even monitor - I have no idea ) In miner console under Linux I still show only err. Maybe ask in mmpOS discord about solution?

**Comment by Customayzer** [comment]
My hash a770 25 too. Thank you for the answer.

**Comment by Customayzer** [comment]
Hi Andriy , haw disable gpu nvidia, and mine only on arc intel ?

**Comment by andru-kun** [comment]
> Hi Andriy , haw disable gpu nvidia, and mine only on arc intel ?

sorry, was not active online for a long time, hope you found a solution(_--opencl-platforms intel_)
