### ISSUE TITLE
Error CL_INVALID_BUFFER_SIZE when calling clCreateBuffer to create state buffer, Failed to start OpenCL threads error on intel 770 16gb

### ISSUE THREAD

**Issue by BabyLFG2024** [andru-kun/wildrig-multi#287]
im trying to run ghostrider algo and i keep getting this error, im not having any other problems on any other algos. 

ive got the latest drivers installed, and opencl is checked in gpu-z

any suggestion on how i can fix this?
![Screenshot (1)](https://github.com/andru-kun/wildrig-multi/assets/156048252/7ed0d1f0-e1db-499d-a79e-343349ebd2d8)

**Comment by andru-kun** [comment]
try set lower intensity, like **-i 1536** or **-i 1024**

**Comment by BabyLFG2024** [comment]
thank you, that solved the problem. much appreciated
