### ISSUE TITLE
Error CL_INVALID_BINARY when calling clCreateProgramWithBinary on Arc A380

### ISSUE THREAD

**Issue by yaoxiaoangry** [andru-kun/wildrig-multi#289]
![1](https://github.com/andru-kun/wildrig-multi/assets/58104783/b7fdbb33-a01d-4677-aff1-c87cc54f4cbd)
<img width="553" alt="捕获" src="https://github.com/andru-kun/wildrig-multi/assets/58104783/f4842aeb-6c54-4091-b308-6810eaf2a96b">

My video card is Arc A380, and the wildrig version is the most recent. I have tried to install 31.0.0101.5084/5085/5333 driver program, but failed to solve the problem.

hope to find the help, thanks!

I'm using the following instructions:
@echo off

:loop
wildrig.exe --algo kawpow --url stratum+ssl://rvn.kryptex.network:8888 --user ***************** --pass x

if ERRORLEVEL 1 goto custom
timeout /t 5
goto loop

:custom
echo Custom command here
timeout /t 5
goto loop

**Comment by andru-kun** [comment]
interesting, can you please check any other algorithm if it works? Just run start-Radiant.bat or start-SkyDoge.bat that included in miner archive.

**Comment by yaoxiaoangry** [comment]
> interesting, can you please check any other algorithm if it works? Just run start-Radiant.bat or start-SkyDoge.bat that included in miner archive.

<img width="567" alt="radiant" src="https://github.com/andru-kun/wildrig-multi/assets/58104783/f2434496-95f1-4a57-b181-4ccfe0a12a55">
<img width="543" alt="skydoge" src="https://github.com/andru-kun/wildrig-multi/assets/58104783/d406dd71-2d7d-49de-b963-1d27e4d63f8d">
the first picture is radiant, the next picture is skydoge, still can't work QAQ

**Comment by andru-kun** [comment]
this is pretty odd situation, since card have same architecture as all other Alchemist cards. Will check it a bit later more

**Comment by yaoxiaoangry** [comment]
thanks, bro, looking forward your message~

**Comment by AlienMiner303** [comment]
I have the same issue with mine as well, any fix yet?

**Comment by andru-kun** [comment]
> I have the same issue with mine as well, any fix yet?

unfortunately no, looks like A380 needs different binary kernel despite it's the same architecture as A580, A750 and so on. Those cards are tested and works fine. Probably this happens on Windows, don't know yet since I don't have A380.

**Comment by AlienMiner303** [comment]
sounds good thank you for the reply

**Comment by andru-kun** [comment]
> sounds good thank you for the reply

well, I found a reason, but not sure when I will release new version with a fix :) But I hope this will happen this week

**Comment by AlienMiner303** [comment]
that would be awesome! thanks for the info

**Comment by andru-kun** [comment]
should be finally fixed in 0.40.7+
