### ISSUE TITLE
KAAPOW algorithm (new RVN)

### ISSUE THREAD

**Issue by MaynardMiner** [andru-kun/wildrig-multi#29]
RVN is swithcing to KAAPOW algorithm soon. May want to try to add.

https://github.com/RavenProject/Ravencoin/tree/develop/src/crypto/ethash

https://github.com/RavenProject/Ravencoin/commit/2e6a132e4c43edc9204007356fa4d65aeedd6be9

**Comment by andru-kun** [comment]
done, 0.22.0
