### ISSUE TITLE
How to set parameters independently for multiple GPUs? What is the specific command? ?

### ISSUE THREAD

**Issue by tolygbaby** [andru-kun/wildrig-multi#290]
How to set parameters independently for multiple GPUs? What is the specific command? ?

**Comment by andru-kun** [comment]
just use comma for separation, e.g. _--gpu-core-clock 1100,1100,1200,1300_

**Comment by andru-kun** [comment]
it should be ok

**Comment by tolygbaby** [comment]
thanks

Andrii ***@***.***> 于 2024年3月1日周五 04:40写道：
