### ISSUE TITLE
Wildrig is not using all GPUs ?

### ISSUE THREAD

**Issue by goodthebest** [andru-kun/wildrig-multi#294]
@andru-kun 
I've 3 amd GPUs installed but wildrig-multi is only using one GPU, is there a way or any flag to be used to make sure all GPUs are being used for hashing? Below is the screenshot

![image](https://github.com/andru-kun/wildrig-multi/assets/1715740/69fe6808-cb02-4cdb-b8b8-a2fe4c812f8b)

**Comment by andru-kun** [comment]
it uses all gpu's, but those two probably crashed, tune your OC settings better

**Comment by goodthebest** [comment]
Can you please elaborate where I can make changes in OC (opencl) settings? Any flags to be used with miner?

Is it possible to force miner to use a particular gpu only out of those three 0, 1, 2?

**Comment by andru-kun** [comment]
well, wildrig have no parameters to OC AMD gpu's, so do it via your mining OS or 3rd party tools. What about using particular gpu, use parameter -d, like _-d 2_ or _-d 0,2_
