### ISSUE TITLE
How do I get a payout for mining?

### ISSUE THREAD

**Issue by jamal-wia** [andru-kun/wildrig-multi#296]
How do I get a payout for mining? I started mining about 24 hours ago, but so far I haven’t received a single payout. I’m new to mining, so I might have set something up incorrectly. I decided to mine NEXA and launched mining through a .bat file, having previously replaced the wallet id in it with my own (I got the id of my wallet from the “Receive” section in the NEXA wallet). I didn’t change anything else, checked the balance every few hours, but didn’t receive any payouts.

**Comment by jamal-wia** [comment]
![image](https://github.com/andru-kun/wildrig-multi/assets/38330286/e4912ff0-54b2-474b-a378-c454c51e983e)

**Comment by jamal-wia** [comment]
![image](https://github.com/andru-kun/wildrig-multi/assets/38330286/5f0b3caf-fe18-436f-9b4a-88ebec3d26a0)

**Comment by andru-kun** [comment]
check rplant pool message:
"the first payment will be made 7 days after the start of mining. the developers of the coin require 5000 confirmations of blocks"

also you can search more details in their telegram group. Also use some other miner for nexapow, wildrig is a bad choice right now.
