### ISSUE TITLE
meowpow: Problem during devfee mining

### ISSUE THREAD

**Issue by RainbowMiner** [andru-kun/wildrig-multi#301]
After the devfee mining starts during meowpow mining, only rejects happen:

```
[12:24:31] devfee mining started
...
[12:25:06] oh my gosh! Too many rejects, disconnect
[12:25:12] oh my gosh! Too many rejects, disconnect
..
```

**Comment by andru-kun** [comment]
oh boi, thanks for report, will fix and reupload, missed one thing there...

**Comment by andru-kun** [comment]
done, should be fine now )

**Comment by YastrebX** [comment]
Have the same issue with memehash

**Comment by andru-kun** [comment]
> Have the same issue with memehash

they changed the algo, so it won't work anymore
