### ISSUE TITLE
WildRig Multi 0.40.8 and Radeon 5700XT: UNKNOWN_ERROR when calling clGetPlatformIDs for number of platforms

### ISSUE THREAD

**Issue by Anon56986** [andru-kun/wildrig-multi#304]
Hello. WildRig Multi 0.40.8. After updating the driver for the Radeon 5700XT to version 24.8.1, the miner gives an error when starting:

```
Error UNKNOWN_ERROR when calling clGetPlatformIDs for number of platforms
[10:22:41] Failed to find OpenCL platform
[10:22:42] Failed to find supported AMD/NVIDIA/INTEL devices
```

**Comment by andru-kun** [comment]
drivers are broken, use DDU tool to uninstall them and reinstall from scratch

**Comment by Anon56986** [comment]
Removing and installing the driver did not help.

`[18:30:15] Failed to find supported AMD/NVIDIA/INTEL devices`

**Comment by andru-kun** [comment]
> Removing and installing the driver did not help.
> 
> `[18:30:15] Failed to find supported AMD/NVIDIA/INTEL devices`

nothing I can do here if AMD broken their own drivers and any call to an OpenCL fails. Use older drivers then.

**Comment by Anon56986** [comment]
It's strange, but when I downloaded the archive WildRig Multi 0.40.8, the miner started working.

**Comment by andru-kun** [comment]
> It's strange, but when I downloaded the archive WildRig Multi 0.40.8, the miner started working.

strange things happen )
