### ISSUE TITLE
Error mining nexapow@nicehash with ADM RDNA1 / RDNA2

### ISSUE THREAD

**Issue by UselessGuru** [andru-kun/wildrig-multi#307]
Wildrig-v0.40.9\wildrig.exe --algo nexapow --api-port 4005 --url stratum+tcps://nexapow.auto.nicehash.com:443 --user ###############################.############### --pass x --multiple-instance --opencl-platform 1 --opencl-devices 0

 ###################################
 #################  ################
 ################    ############### * ABOUT:    WildRig/0.40.9
 ####   #########    #########   ### * CPU:      Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
 ####     #######    #######     ### * ALGO:     nexapow
 ####   #  ######    ######      ### * POOL #1:  nexapow.auto.nicehash.com:443
 ####   ##  #####    #####  ##   ### * API PORT: 4005
 ####   ##   #####  #####   ##   ### * COMMANDS: hashrate
 ####   ##   #####  #####  ###   ###
 ####   ###  #####  #####  ###   ###   devfee: 0.75%
 ####   ###  ####    ####  ###   ###   send-stale: no
 ####   ###   ###    ###   ###   ###   watchdog: disabled
 ####   ##    ##      ##    ##   ###
 ####      #####  ##  #####      ###
 ####   #   ###  ####  ###   #   ###
 ####   ##       ####       ##   ###
 ####   #####  #      #  #####   ###
 ####   #####  ###  ###  #####   ###
 ####                            ###
 ############   ##  ##   ###########
 #############   #  #   ############
  #############        #############
      ###########    ###########
          ##################

[18:38:37] Initializing GPUs...
[18:38:37] GPU #0: AMD Radeon RX 5700 XT [busID: 8] [arch: gfx1010]
[18:38:37] threads: 1, intensity: 22, cu: 40, mem: 8176Mb
[18:38:38] Start mining
Exception Code: 0xC0000005
0x00007FF7F5CBF449, c:\Users\UselessGuru\Desktop\UG-Miner\Bin\Wildrig-v0.40.9\wildrig.exe(0x00007FF7F5C10000) + 0xAF449 byte(s)
0x00007FF7F5CBCA7A, c:\Users\UselessGuru\Desktop\UG-Miner\Bin\Wildrig-v0.40.9\wildrig.exe(0x00007FF7F5C10000) + 0xACA7A byte(s)
0x00007FF7F5CBFD57, c:\Users\UselessGuru\Desktop\UG-Miner\Bin\Wildrig-v0.40.9\wildrig.exe(0x00007FF7F5C10000) + 0xAFD57 byte(s)
0x00007FF7F5CBC233, c:\Users\UselessGuru\Desktop\UG-Miner\Bin\Wildrig-v0.40.9\wildrig.exe(0x00007FF7F5C10000) + 0xAC233 byte(s)
0x00007FF7F5D52E84, c:\Users\UselessGuru\Desktop\UG-Miner\Bin\Wildrig-v0.40.9\wildrig.exe(0x00007FF7F5C10000) + 0x142E84 byte(s)
0x00007FF7F5D485B7, c:\Users\UselessGuru\Desktop\UG-Miner\Bin\Wildrig-v0.40.9\wildrig.exe(0x00007FF7F5C10000) + 0x1385B7 byte(s)
0x00007FF7F5D48BA5, c:\Users\UselessGuru\Desktop\UG-Miner\Bin\Wildrig-v0.40.9\wildrig.exe(0x00007FF7F5C10000) + 0x138BA5 byte(s)
0x00007FF7F5CB1AF4, c:\Users\UselessGuru\Desktop\UG-Miner\Bin\Wildrig-v0.40.9\wildrig.exe(0x00007FF7F5C10000) + 0xA1AF4 byte(s)
0x00007FF7F5D0E07C, c:\Users\UselessGuru\Desktop\UG-Miner\Bin\Wildrig-v0.40.9\wildrig.exe(0x00007FF7F5C10000) + 0xFE07C byte(s)
0x00007FF7F5E84415, c:\Users\UselessGuru\Desktop\UG-Miner\Bin\Wildrig-v0.40.9\wildrig.exe(0x00007FF7F5C10000) + 0x274415 byte(s)
0x00007FFAED4D259D, C:\WINDOWS\System32\KERNEL32.DLL(0x00007FFAED4C0000) + 0x1259D byte(s), BaseThreadInitThunk() + 0x1D byte(s)
0x00007FFAEF04AF38, C:\WINDOWS\SYSTEM32\ntdll.dll(0x00007FFAEEFF0000) + 0x5AF38 byte(s), RtlUserThreadStart() + 0x28 byte(s)

**Comment by andru-kun** [comment]
NiceHash is not supported for nexapow, since they use unsupported protocol for it.

**Comment by UselessGuru** [comment]
>> NiceHash is not supported for nexapow, since they use unsupported protocol for it.

Thank you. A meaningful error message would help. :-)

**Comment by andru-kun** [comment]
yeah, need to implement that. Right now it just crashes when trying to read some unavailable data or something, since at time nexapow arrived I have implemented it in hurry and didn't tuch after xD
