### ISSUE TITLE
"Unwanted module" error

### ISSUE THREAD

**Issue by DanielKOcean** [andru-kun/wildrig-multi#31]
I face this error when starting the miner:
`Unwanted module "C:\Program Files\Common Files\Crypto Pro\AppCompat\cpcrypt.dll"`
Looks like that miner tries to use .dll from some other software that is installed on my PC.
```
Windows 10 18363.836

.\print-devices.bat
PLATFORMS:
#0: Advanced Micro Devices, Inc.

DEVICES:
GPU #0 [BusID: #3] AMD Radeon RX 5600 XT (arch: gfx1010, cu: 18, mem: 6128Mb)

.\wildrig.exe --version
WildRig 0.24.1
 built on May 17 2020 with MSVC 2015
 features: x86_64 AES-NI

libuv/1.21.0
libmicrohttpd/0.9.63
```

**Comment by andru-kun** [comment]
Well, this is not a miner trying to use your software, this is your software trying to inject its dll into any app on PC. If you can disable it specifically for wildrig, please do. Otherwise miner won't work, since protection module thinks this is a threat.

**Comment by DanielKOcean** [comment]
Holy... Ok, so I'll try to disable this behavior. Don't you know how to disable it for a specified app like wildrig?

**Comment by andru-kun** [comment]
This is a question to devs of that app, unfortunately I have no idea even what is it :)

**Comment by DanielKOcean** [comment]
Thanks a lot anyway.

**Comment by DanielKOcean** [comment]
Not an issue of the miner.
