### ISSUE TITLE
v0.41.0 (Windows): No hashrate for sha256csm  with Nvidia GT750

### ISSUE THREAD

**Issue by UselessGuru** [andru-kun/wildrig-multi#310]
`Wildrig-v0.41.0\wildrig.exe --algo sha256csm --watchdog --api-port 4003 --url stratum+tcp://sha256csm.mine.zergpool.com:3340 --user ################### --pass c=BTC,ID=############ --multiple-instance --opencl-platform 0 --opencl-devices 2`

┫0 days 00:00:19┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫Statistics┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ID Name                         Hashrate Temp  Fan  Pwr   Eff CClk MClk     A   R   I
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 #2 GeForce GTX 750 Ti           n/a MH/s  32C  30%   1W   nan  135  405     -   -   -
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 10s:                            n/a MH/s Power:      1W            Accepted:        -
 60s:                            n/a MH/s                           Rejected:        -
 15m:                            n/a MH/s                           Ignored:         -
┫0 days 00:00:19┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫Statistics┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ID Name                         Hashrate Temp  Fan  Pwr   Eff CClk MClk     A   R   I
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 #2 GeForce GTX 750 Ti           n/a MH/s  32C  30%   1W   nan  135  405     -   -   -
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 10s:                            n/a MH/s Power:      1W            Accepted:        -
 60s:                            n/a MH/s                           Rejected:        -
 15m:                            n/a MH/s                           Ignored:         -
┫0 days 00:00:19┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[11:44:10] GPU #2: hangs in OpenCL kernel for more than 30 seconds, exit
[11:44:11] GPU #2: some critical error happened
[11:44:12] exiting...
[11:44:12] GPU #2: shutting down...
[11:44:52] HTTP Daemon[192.168.111.100] stopped
[11:44:52] HTTP Daemon[localhost] stopped
[11:44:52] HTTP Daemon[127.0.0.1] stopped

**Comment by andru-kun** [comment]
what if try custom lower intensity?

**Comment by UselessGuru** [comment]
--gpu-intensity 28 works

**Comment by andru-kun** [comment]
thanks, will lower intensity for low end cards a bit. On RX550 default was working fine as I remember, didn't expect hang on nvidia

**Comment by UselessGuru** [comment]
Fixed in 0.41.1.

Thank you!
