### ISSUE TITLE
v0.41.2 (windows) reports as v0.41.3

### ISSUE THREAD

**Issue by UselessGuru** [andru-kun/wildrig-multi#311]
Wildrig-v0.41.2\wildrig.exe --algo x16rv2 --api-port 4005 --url stratum+tcp://x16rv2.mine.zergpool.com:3637 --user ################### --pass c=BTC,ID=#####  --multiple-instance --opencl-platform 1 --opencl-devices 0

Downloaded from
https://github.com/andru-kun/wildrig-multi/releases/download/0.41.2/wildrig-multi-windows-0.41.2.zip

![image](https://github.com/user-attachments/assets/010d7994-7cf4-4bf4-93a1-39e90c68a2e6)

**Comment by andru-kun** [comment]
yeah, known issue because of reupload, will be fixed next release )
