### ISSUE TITLE
Wildrig-v0.48.1 (windows): Cosmetic error messages?

### ISSUE THREAD

**Issue by UselessGuru** [andru-kun/wildrig-multi#313]
![image](https://github.com/user-attachments/assets/5ca408a6-fbcf-4849-a774-81fa968a2e25)

![image](https://github.com/user-attachments/assets/1e8b934a-5b1a-4025-abd2-5c22ad831597)

Command line used:
e.g.:
Bin\Wildrig-v0.48.1\wildrig.exe --algo megabtx --watchdog --api-port 4004 --url stratum+tcp://megabtx.mine.zergpool.com:3557 --user ############################ --pass c=BTC,ID=################ --multiple-instance --opencl-platform 0 --opencl-devices 1

Same errors with Ghostrider & X21 (possibly others)
Errors occur on RX750, Gt1030 and GTX3600 and also AMD cards.

**Comment by andru-kun** [comment]
damn, with obsolete algorithms removed extra few lines of code that was used for auto-tuning in some cases xD Thanks for the report, will fix in the next release )

**Comment by andru-kun** [comment]
should be fixed in 0.41.9
