### ISSUE TITLE
Unwanted module Error

### ISSUE THREAD

**Issue by ProofOfRight** [andru-kun/wildrig-multi#34]
Hello dev!

I got the error after start the miner:
`Unwanted module "C:\Program Files (x86)\InfoTeCS\ViPNet CSP\Itccspbs64.Dll"...`
So i think it's about a SSL connection? How can i fix it?

**Comment by ProofOfRight** [comment]
Done

**Comment by andru-kun** [comment]
Looks like you found info, that this is protection subsystem of miner, tgar doesn't like any app to inject their dll in miner :)
