### ISSUE TITLE
Seems that x33 algo will become useless tomorrow

### ISSUE THREAD

**Issue by Shekelme** [andru-kun/wildrig-multi#36]
Qureno team implemented 17 unique algorithms inside the blockchain.
The kernel will choose which algorithm to use for the future block. RThere will be a random selection of one of the unique algorithms: x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49.
They will prepare the release tomorrow.

**Comment by andru-kun** [comment]
yeah, I saw ) But better to post something like this on discord/bitcointalk
