### ISSUE TITLE
Print devices feature request

### ISSUE THREAD

**Issue by luc1an24** [andru-kun/wildrig-multi#39]
Hi
I am writing to you because I am having issues cross referencing GPU's on rigs. 
Could you please include PCIE BusID to the output?
Like so for example:
GPU #0: GeForce GTX 1070 Ti  (busId: 5, arch: sm61,    cu: 19, mem: 8192Mb)

This would be really appreciated since this is causing issues to users of your program in NiceHash Miner.
Thank you!

**Comment by andru-kun** [comment]
oh, forgot to add that into *--print-devices*, will do that in next release.

**Comment by luc1an24** [comment]
Thank you!

**Comment by luc1an24** [comment]
Hi
Do you have any ETA when this feature will be released?
Thank you

**Comment by andru-kun** [comment]
Hi,
Can't tell exactly, since I'm not developing anything right now. But hope to release something before December 18, when I go on vacation.
