### ISSUE TITLE
little problem

### ISSUE THREAD

**Issue by screeni** [andru-kun/wildrig-multi#4]
hi Andru new problem !

![capture-m](https://user-images.githubusercontent.com/29159147/50361520-20ff9500-0564-11e9-9531-6d008b299356.PNG)

config is Windowx 10 -  64 vs 1809 - 3xVega64

thanks for your time

**Comment by andru-kun** [comment]
Hi, 0.15 version is only for MTP algo, other can be buggy. Use 0.14.0 for x16r. Also --watchdog is not recommended because of AMD drivers, they can hang and not let miner exit

**Comment by screeni** [comment]
thanks for your time
