### ISSUE TITLE
Failed to find AMD/NVIDIA device with OpenCL support. Possible driver issues or wrong vendor driver

### ISSUE THREAD

**Issue by khudysh** [andru-kun/wildrig-multi#47]
Hello Andrii, i have error: "Failed to find AMD/NVIDIA device with OpenCL support. Possible driver issues or wrong vendor driver"
gpu: 1060 3gb
tried to mine Combode, using --opencl-launch 20x128 --opencl-threads 3 doesn't help

![image](https://user-images.githubusercontent.com/60621694/103677713-b2979f00-4f93-11eb-8a89-4923807fc8fe.png)

**Comment by andru-kun** [comment]
Hi, this you get with default start-combode.bat? If so, looks like your driver is broken and there is no OpenCL installed properly for NVIDIA.

**Comment by catursawah** [comment]
wkwkwkwkw mining with google colab
