### ISSUE TITLE
RX 6800

### ISSUE THREAD

**Issue by UspesenRudar** [andru-kun/wildrig-multi#49]
20:43:05] GPU #0: AMD Radeon RX 6800 [busID: 3] [arch: gfx1030]
[20:43:05] threads: 2, intensity: 18, worksize: 256/1024, cu: 30, mem: 16368Mb
[20:43:06] architecture "gfx1030" not supported
[20:43:07] Failed to start OpenCL threads
 * VERSIONS: WildRig/0.28.2 beta libuv/1.21.0 OpenCL/2.0 MSVC/2015

**Comment by platinum4** [comment]
Do you need a rig to dev on with a Navi card?

**Comment by andru-kun** [comment]
@platinum4 well, I need my own card for proper tuning and for not disclosing OpenCL source code on remote machines :) Probably I will try some offline compilation in future, but have no idea when.

**Comment by Cminer3207** [comment]
The 6800 isn’t that much more expensive than a 3070... 
Without WildRig, AMD doesn’t have a BigNavi that can compete. The 5700s are outclassed all day by Nvidia...

**Comment by Wwurzer** [comment]
Please ad the rx 6800xt to the supported cards! It seems to be the best option for VBK mining and it is available while RTX 30 are most out of stockor for a ridiculously high price

**Comment by RGlabs84** [comment]
we still need these card supported =(

**Comment by andru-kun** [comment]
> we still need these card supported =(

Well, I finally ordered 6800XT, so probably will do something in a few weeks(need to wait for card to be shipped) :)

**Comment by MonroeLiang** [comment]
> > 我们仍然需要支持这些卡 =(
> 
> 好吧，我终于订购了 6800XT，所以可能会在几周内做一些事情（需要等待卡发货）:)

CAN I6800xt be uesd

**Comment by andru-kun** [comment]
fixed in 0.29.0
