### ISSUE TITLE
Version 15.0.3 & 15.0.6 crash driver

### ISSUE THREAD

**Issue by UselessGuru** [andru-kun/wildrig-multi#5]
Command line used:

wildrig_avx.exe --algo=x16r --api-port=4002 --url=stratum+tcp://x16r.mine.blazepool.com:3636 --user=******************************* --pass=ID=multipoolminer,c=BTC --opencl-threads 2 --opencl-launch 20x0 --donate-level 1 --opencl-platform=1 --opencl-devices=1

Device 1 is an RX 570, driver version 18.2.2 & 18.2.3

Miner starts, and after approx 5 seconds the driver crashes (entry in eventlog). -> no hashrate

Version 14.0 beta works fine with the same parameters in the the same rig.

**Comment by andru-kun** [comment]
as was said before, 0.15.x.x is only for mtp algo, everything else maybe broken

**Comment by UselessGuru** [comment]
> everything else maybe broken

I see - thank you!
