### ISSUE TITLE
No hash rate on SHA256csm

### ISSUE THREAD

**Issue by unclevito2017** [andru-kun/wildrig-multi#50]
i tried to mine with Nvidia GTX 970 and GTX1050 and RX560 AMD and no hash rate from the GPU's or the CPU's. No load on any of the devices. Any suggestions

**Comment by andru-kun** [comment]
What pool do you use? Probably wrong url/port and you just don't get any job to solve

**Comment by unclevito2017** [comment]
The coin does not have a pool yet, you have to mine the wallet locally
(localhost)

**Comment by andru-kun** [comment]
solo mining is not suppoeted that's why gpu's are not hashing

**Comment by old80** [comment]
> What pool do you use? Probably wrong url/port and you just don't get any job to solve

All the miners who pursuit mining rig´s cant take advantage from any GPU, cause of it´s low hashrate on WildRig!!! they are abandoning RTM mining cause of it´s low profits and high energy cousts.
