### ISSUE TITLE
Limit GPU usage ? 

### ISSUE THREAD

**Issue by tonarii** [andru-kun/wildrig-multi#52]
Hi, is it possible to use function to limit the gpu usage, like -gpow or something like that ?
If yes, how can write it inside the WildRigMulti.ps1 file ?
(i'm on AMD)
Thanks

**Comment by andru-kun** [comment]
Hi, the only way to do it is `--opencl-launch` parameter. Just set lower intensity with it.

**Comment by tonarii** [comment]
Thanks a lot i will try.

**Comment by tonarii** [comment]
Thanks a lot.
Edit: I'm sorry but where can i find this parameter ? I search into my logs and on the web but i can't find what to put, like the scale of the parameter for instance.
I run a RX 5700XT.

**Comment by andru-kun** [comment]
on start miner shows your intensity by default(right in the strings where gpu initializing). So just take that value and decrease it. E.g. if it was 19, set `--opencl-launch 18`` and so on, until you get desired result. But hashrate can decrease dramatically.

**Comment by tonarii** [comment]
ok perfect ! thanks a lot for this fast and complet explanation ;)
