### ISSUE TITLE
Skein Algorithm

### ISSUE THREAD

**Issue by imrecsoka** [andru-kun/wildrig-multi#53]
Helllo, i notice there is a Xevan and Skein 2 algorithm, is there perhaps a Skein algorithm?
Im trying to mine Digibyte which is minable using SGminer and CGminer but i have issues with a new device so only older devices work.
I just thought i would try a newer miner instead.

**Comment by andru-kun** [comment]
well, skein is ASIC minable, so not much sense to implement it :)
