### ISSUE TITLE
AMD 5700xt not supported - Algo x25x

### ISSUE THREAD

**Issue by JABirchall** [andru-kun/wildrig-multi#56]
Your readme says 5700xt is supported, but when I run the miner, it says it not supported.

**Comment by Fantastic-Dave** [comment]
same for me 
![image](https://user-images.githubusercontent.com/1854909/116076346-05ed4480-a68c-11eb-828b-34fcbd45e520.png)

**Comment by nwalk7800** [comment]
This problem appeared for me after upgrading to the April drivers.  Rolling back to March drivers fixed it.

**Comment by JABirchall** [comment]
0.29 fixed this for me.
