### ISSUE TITLE
WildRig Multi 0.15.0.7 mtp 3% donation!!!

### ISSUE THREAD

**Issue by Ivvi30** [andru-kun/wildrig-multi#6]
I would like less commission, or the ability to turn off or down, as in previous versions. Because in this version I can not reduce the commission 3%!

**Comment by andru-kun** [comment]
it will be default 2%(with possibility to set 1%) in 2019. Anyway, there is no sense to use WildRig for ZCoin right now, because there is already NVIDIA miner with everything done on GPU while WildRig still uses CPU for some parts of algo, and I have no plans to change this in next few weeks or so.
