### ISSUE TITLE
WildRig/0.29.0 beta (Win 10): not working on RX5700, 0.28.3 is working

### ISSUE THREAD

**Issue by UselessGuru** [andru-kun/wildrig-multi#64]
`Bin\Wildrig-v0.29.0\wildrig.exe --algo hmq1725 --api-port=4002 --url=hmq1725.mine.zergpool.com:3747 --user=#######################.########## --pass=Blackbox,c=BTC,pl=0 --multiple-instance --opencl-threads auto --opencl-launch auto --opencl-platforms=0 --opencl-devices=0`
 \* VERSIONS: WildRig/0.29.0 beta libuv/1.21.0 OpenCL/2.0 MSVC/2015
 \* CPU:      Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
 \* ALGO:     hmq1725
 \* POOL \#1:  hmq1725.mine.zergpool.com:3747
 \* API PORT: 4002
 \* COMMANDS: hashrate, statistics, pause, resume
[14:12:41] donation: 1%
[14:12:41] send-stale: no
[14:12:41] watchdog: disabled
[14:12:41] temp limits: 60C..85C
[14:12:41] initializing GPUs...
[14:12:41] RDNA/RDNA2 gpu's are not fully optimized yet for chosen algorithm
[14:12:41] GPU \#0: AMD Radeon RX 5700 XT [busID: 5] [arch: gfx1010]
[14:12:41] threads: 2, intensity: 20, worksize: 64/256, cu: 40, mem: 8176Mb
[14:12:42] Error CL_BUILD_PROGRAM_FAILURE when calling clBuildProgram
[14:12:43] Error CL_BUILD_PROGRAM_FAILURE when calling clBuildProgram
[14:12:44] Error CL_INVALID_KERNEL_NAME when calling clCreateKernel for kernel 'keccak_256_32'
[14:12:45] Failed to start OpenCL threads

`Bin\Wildrig-v0.28.3\wildrig.exe --algo hmq1725 --api-port=4002 --url=hmq1725.mine.zergpool.com:3747 --user=#######################.########## --pass=Blackbox,c=BTC,pl=0 --multiple-instance --opencl-threads auto --opencl-launch auto --opencl-platforms=0 --opencl-devices=0`
 \* VERSIONS: WildRig/0.28.3 beta libuv/1.21.0 OpenCL/2.0 MSVC/2015
 \* CPU:      Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
 \* ALGO:     hmq1725
 \* POOL \#1:  hmq1725.mine.zergpool.com:3747
 \* API PORT: 4002
 \* COMMANDS: hashrate, statistics, pause, resume
[14:12:56] donation: 1%
[14:12:56] send-stale: no
[14:12:56] watchdog: disabled
[14:12:56] temp limits: 60C..85C
[14:12:56] initializing GPUs...
[14:12:56] AMD Navi(gfx1010) not fully optimized yet for chosen algorithm
[14:12:56] GPU <#0: AMD Radeon RX 5700 XT [busID: 5] [arch: gfx1010]
[14:12:56] threads: 2, intensity: 20, worksize: 64/256, cu: 40, mem: 8176Mb
[14:12:58] use pool hmq1725.mine.zergpool.com:3747 51.210.180.98
[14:12:58] Stratum set raw difficulty to 1560.0000
[14:12:58] new job from hmq1725.mine.zergpool.com:3747 diff 102.24M/255.18G
[14:12:58] block: 97,038        job target: 0x0000002a02762762

I tried the following algos, all failing:
Hmq1725, KawPoW, Lyra2RE3, X21s, MTP, Skein2, X16r, Tribus, SkunkHash, MegaBtx, C11, X17, MegaMec, X16s, Sha256t, Phi,

**Comment by andru-kun** [comment]
What driver version?

**Comment by UselessGuru** [comment]
> What driver version?
2021.3.2 (v0.28.3 works flawlessly)

**Comment by andru-kun** [comment]
I did recompile some kernels, and done this with drivers 2021.5.2, probably AMD broke backward compatibility once again..,

**Comment by UselessGuru** [comment]
Driver was indeed the culprit. I installed 2021.6.2 and all algos (except Lyra2V3) work well on RX580.
maybe you should implement a driver version check and print a warning.

**Comment by JABirchall** [comment]
yea prolly best to print a warning to update drivers as many people kept to old version of and drivers to use 0.28

**Comment by andru-kun** [comment]
@UselessGuru can you please check this [build](https://mega.nz/file/XeoT2QiB#JXQ1rm0ZN3Ad8WPuCi1MABz3M6MD7vKQInhEipHg6Rw)? Recompiled kernels with offline method and used older driver for that.

**Comment by blackice92** [comment]
![Screenshot_20210914-154637.jpg](https://user-images.githubusercontent.com/89813590/133260175-e060a165-b1c0-483b-a38a-4ca326f62b05.jpg)

6800xt,vbk mining ? 🙄

**Comment by andru-kun** [comment]
@blackice92 what driver version it is? OpenCL 21.30 or OpenCL 20.40?

**Comment by andru-kun** [comment]
or this is ROCm drivers? :)

**Comment by blackice92** [comment]
> @blackice92 what driver version it is? OpenCL 21.30 or OpenCL 20.40?

20.40 (5.6.X.0202)

**Comment by blackice92** [comment]
> or this is ROCm drivers? :)

I have no problems with other miner software.  I want to dig vbk with 6800xt, it leaves 14 dollars per day right now.  I'm a bit unfamiliar with the subject. What is rocm?  Or can you tell me how to do it please :)

**Comment by andru-kun** [comment]
> 20.40 (5.6.X.0202)

Yeah, I thought so. This version of miner needs 21.30... Ok, will try to provide new build with support of old and new drivers. Thanks for the info!

**Comment by blackice92** [comment]
> > 20.40 (5.6.X.0202)
> 
> Yeah, I thought so. This version of miner needs 21.30... Ok, will try to provide new build with support of old and new drivers. Thanks for the info!

![Screenshot_20210914-164439.jpg](https://user-images.githubusercontent.com/89813590/133269795-42f44196-b950-4d57-9632-f02c20062bce.jpg)
![IMG_20210914_164552.jpg](https://user-images.githubusercontent.com/89813590/133269930-b9b23b6f-d920-4f96-871a-46d0fd9b0d26.jpg)

please tell me you have the code to update 😂😂 (6800xt vprogpow 39mh ,source: minestat )

**Comment by andru-kun** [comment]
> please tell me you have the code to update joyjoy (6800xt vprogpow 39mh ,source: minestat )

nah, 39MH/s is for kawpow, vprogpow 3 times slower :)

**Comment by blackice92** [comment]
> nah, 39MH/s is for kawpow, vprogpow 3 times slower :)

https://minerstat.com/compare/rx-6800-xt-vs-rtx-3090?units1=1&units2=1&lang=tr


😱at the bottom.

**Comment by andru-kun** [comment]
> 
> 
> > nah, 39MH/s is for kawpow, vprogpow 3 times slower :)
> 
> https://minerstat.com/compare/rx-6800-xt-vs-rtx-3090?units1=1&units2=1&lang=tr
> 
> screamat the bottom.

3090 is twice as fast as 6800XT on Eth, so pretty ok 22Mh/s vs 11MH/s )

**Comment by MonroeLiang** [comment]
> > nah, 39MH/s is for kawpow, vprogpow 3 times slower :)
> 
> https://minerstat.com/compare/rx-6800-xt-vs-rtx-3090?units1=1&units2=1&lang=tr
> 
> 😱at the bottom.

if you find ang way increase  hashrate ,let us know

**Comment by MonroeLiang** [comment]
<img width="1720" alt="微信截图_20210915222337" src="https://user-images.githubusercontent.com/25814796/133452098-0e2248c3-ab83-4cbf-8a1b-2a2fd9a6d947.png">

**Comment by UselessGuru** [comment]
> @UselessGuru can you please check this build?

I had to revert to 2021.3.2 (newer builds hav device detection issues).
0.29.1 runs fine in all tests I ran.
Win 10 / x64
AMD 2021.3.2: 1x RX5700, 1x RX580 8GB, 1x RX 200 Series
NVidia 471.96: 1x GTX1660 Super, 1x GTX 750

**Comment by andru-kun** [comment]
should be fixed in 0.30.0
