### ISSUE TITLE
6800xt dig vbk Hashrate  is 15M

### ISSUE THREAD

**Issue by MonroeLiang** [andru-kun/wildrig-multi#65]

**Comment by MonroeLiang** [comment]
6800xt is 39M on minerstar for vbk

**Comment by blackice92** [comment]
> 

what program are you using?

**Comment by andru-kun** [comment]
and what value do you expect? :) Minerstat shows kawpow hashrate, not a vprogpow

**Comment by MonroeLiang** [comment]
> > 
> 
> 你在用什么程序？



> > 
> 
> 你在用什么程序？


/
就是wildrig-multi
