### ISSUE TITLE
AMD 6700 xt CL_build_program_failure when calling clbuildprogram

### ISSUE THREAD

**Issue by arc361** [andru-kun/wildrig-multi#66]
Hey getting this issue, been trying the lastest AMD drivers and have also tried 21.6.1 driver as well

This is occuring on rvncoin lite x16r

**Comment by arc361** [comment]
Sapphire Nitro+ AMD Radeon RX 6700 XT Gaming OC Video Card, 12GB GDDR6 HDMI / Triple DP (11306-01-20T)

**Comment by andru-kun** [comment]
Thanks for report! Looks like found a reason. Will work on a solution,

**Comment by arc361** [comment]
thank you so much!

**Comment by Zekealot** [comment]
I'm getting the same error with an RX 6600XT (Sapphire Pulse 8gb) running 21.8.2 drivers. Would downgrading the driver help or will that not work either?

**Comment by andru-kun** [comment]
> I'm getting the same error with an RX 6600XT (Sapphire Pulse 8gb) running 21.8.2 drivers. Would downgrading the driver help or will that not work either?

It won't, but there is a beta already working. If you are using Windows, here is a [link](https://mega.nz/file/CbggzSrY#t3RFZrS-IxwmxeB4V1jN-sirKNOhADe12M4VD73A_PY). Later will release it on github.

**Comment by Zekealot** [comment]
> It won't, but there is a beta already working. If you are using Windows, here is a [link](https://mega.nz/file/CbggzSrY#t3RFZrS-IxwmxeB4V1jN-sirKNOhADe12M4VD73A_PY). Later will release it on github.

Thank you, that's working for me :)

**Comment by ezio2code** [comment]
Can't get the RX 6600 XT to work.
Also both 6600 and 6700 are not optimized and can't barely hash.

Is there gonna be an update for them ?
Regards

**Comment by andru-kun** [comment]
> 
> 
> Can't get the RX 6600 XT to work.
> Also both 6600 and 6700 are not optimized and can't barely hash.
> 
> Is there gonna be an update for them ?
> Regards

did you try link above with beta-version that should work?

**Comment by ezio2code** [comment]
Yes, it's working for the 6700 but the hash is so low and all over the place, and keeps on pumping invalid shares.

**Comment by andru-kun** [comment]
should be fixed in 0.30.0
