### ISSUE TITLE
ghostrider not working properly on AMD RX 5700 XT

### ISSUE THREAD

**Issue by Fantastic-Dave** [andru-kun/wildrig-multi#71]
i have a rx 5700 xt i just ran the example batch to mine RTM to your dev fund on rplant pool.
i keep getting lots of errors
such as 
![image](https://user-images.githubusercontent.com/1854909/140030920-8d9ee2d5-8cb1-4876-8acd-3a6ce4cace2a.png)

and

![image](https://user-images.githubusercontent.com/1854909/140031187-7788dbda-8d6c-4ada-bf6b-b4a6a11a009b.png)

**Comment by andru-kun** [comment]
Looks like your gpu is crashing because of OC profile or voltage

**Comment by Fantastic-Dave** [comment]
![image](https://user-images.githubusercontent.com/1854909/140033250-0293532e-af43-4fb0-b1c5-d74a61daf662.png)
its not overclocked

**Comment by andru-kun** [comment]
hmm, this is linux?

**Comment by andru-kun** [comment]
hmm, what version of driver is it exactly?

**Comment by Fantastic-Dave** [comment]
![image](https://user-images.githubusercontent.com/1854909/140043989-4199bf5b-7724-4856-8778-b47ca7dec43c.png)

**Comment by Fantastic-Dave** [comment]
im gonna install the latest driver and see if that fixes it

**Comment by Fantastic-Dave** [comment]
i just updated to driver version 21.10.4 on windows 11. that didnt fix it.

**Comment by andru-kun** [comment]
You run just start-raptoreum.bat?

**Comment by andru-kun** [comment]
Can you show what it shows you at start?

**Comment by dastardlyman12** [comment]
fantastic dave - try running the core of the 5700 much slower. i use a lot of 5700s for mining but they are all at 1250 ish core and at 840mv or less core volts. your settings are at best very inefficient IMO and at worse it could be the actual problem here . . . .

**Comment by Fantastic-Dave** [comment]
[wildrig-raptorium-5700xt.log](https://github.com/andru-kun/wildrig-multi/files/7486454/wildrig-raptorium-5700xt.log)

**Comment by andru-kun** [comment]
> 
> 
> this is the log.
> 
> [wildrig-raptorium-5700xt.log](https://github.com/andru-kun/wildrig-multi/files/7486454/wildrig-raptorium-5700xt.log)

pretty strange. Can you please set lower core clock? My PowerColor 5700XT's do only 1905Mhz in Boost Mode, yours 2049 is too damn high in comparison. Try at least 1650Mhz, this is a Base clock.

**Comment by Fantastic-Dave** [comment]
ok these are the settings and log from said settings.
![image](https://user-images.githubusercontent.com/1854909/140615341-cfde286d-c576-44a2-baef-df46f01332f7.png
[wildrig-raptorium-5700xt.log](https://github.com/andru-kun/wildrig-multi/files/7490774/wildrig-raptorium-5700xt.log)
)

commandline: wildrig.exe --print-full --algo ghostrider --url stratum+tcp://stratum-eu.rplant.xyz:7056 --user RUWqxPjtuh8VP2sYUGLApAZrkMwxbZivfR --pass x > wildrig-raptorium-5700xt.log

**Comment by andru-kun** [comment]
hmm, can you please try also with drivers 20.12.1?

**Comment by andru-kun** [comment]
Oh, damn... I know the reason %) Wait a sec.

**Comment by andru-kun** [comment]
Please run
`setx GPU_MAX_WORKGROUP_SIZE 256`

or put before anything in your bat-file
`set GPU_MAX_WORKGROUP_SIZE 256`

**Comment by Fantastic-Dave** [comment]
when i tried 256 it displayed worksize: 0/256 and did nothing so i experimented...
i tested it with setx GPU_MAX_WORKGROUP_SIZE 2048 and that worked!

![image](https://user-images.githubusercontent.com/1854909/140852458-f4a531f9-7c83-4fa8-8d2b-1cb5624394d5.png)
