### ISSUE TITLE
RTX3060Ti LHR sm_86 Ghostrider problem

### ISSUE THREAD

**Issue by BrunnoBombino** [andru-kun/wildrig-multi#72]
installed latest drivers and cuda, but message in consol: sm_86 not fully optimized. windows x64, rtm gh

**Comment by BrunnoBombino** [comment]
![333](https://user-images.githubusercontent.com/58356489/141279807-f77af883-6402-44e0-b41e-ea5ff4eb9c88.PNG)

**Comment by andru-kun** [comment]
this is not a problem, just a message from miner :) That message is default for nvidia gpu's, because x16 family of hashfuncs are not optimized specifically for nvidia, only for amd. But in case of ghostrider that doesn't matter.
