### ISSUE TITLE
How to switch between SSL and TCP connection timed out

### ISSUE THREAD

**Issue by wyxl0563** [andru-kun/wildrig-multi#76]
![image](https://user-images.githubusercontent.com/94226047/141643221-721a6c91-e765-4620-b9d2-ebd3841185dc.png)

**Comment by wyxl0563** [comment]
Does RTM not support NVIDIA GPU mining?

**Comment by andru-kun** [comment]
ssl is not supported. What about timed out error - looks like your internet connection is bad. Try to use pool address for Asia.
