### ISSUE TITLE
raptoreum: wildrig.exe: unsupported non-option argument '--user'

### ISSUE THREAD

**Issue by aet08** [andru-kun/wildrig-multi#78]
bat file

@echo off

:loop
wildrig.exe --print-full --algo ghostrider --url stratum+tcps://us.flockpool.com:5555 --user myRTMaddress --pass x

if ERRORLEVEL 1000 goto custom
timeout /t 5
goto loop

:custom
echo Custom command here
timeout /t 5
goto loop

**Comment by le0dime** [comment]
Change `--url` param to `stratum+tcp://us.flockpool.com:4444`
