### ISSUE TITLE
wildrig-multi exited, waiting to cooldown a bit

### ISSUE THREAD

**Issue by Alekk5** [andru-kun/wildrig-multi#8]
Ubuntu AMD support?
![123](https://user-images.githubusercontent.com/47205805/52036757-a8b2c900-253e-11e9-96fe-2b59668b028b.PNG)

**Comment by andru-kun** [comment]
Current release of wildrig no sense to use for mining ZCoin because of two things - need 8Gb of RAM and MerkleTree generation still on CPU. Better to switch to official SGMiner. But you have gpu's with 4Gb, which is no way for MTP algo.
