### ISSUE TITLE
Failed to find supported devices: RX 5600XT after 0.30.2 update, raptoreum

### ISSUE THREAD

**Issue by Sucharr** [andru-kun/wildrig-multi#84]
As in title. 21.10.2 driver (05.10.2021)

**Comment by andru-kun** [comment]
@Sucharr I need a screen

**Comment by andru-kun** [comment]
Oh, nevermind, I see my error, forgot about that ":xnack-" shit in AMD drivers... Will release a fix in a few days.

**Comment by andru-kun** [comment]
fixed in 0.30.3
