### ISSUE TITLE
Feature Request - API -

### ISSUE THREAD

**Issue by mtmtmt123** [andru-kun/wildrig-multi#86]
Can you add a Api to Control Statistics via Network, IP?
Thank you
Good Miner im New in Wildrig

**Comment by andru-kun** [comment]
check help, there is already --api-port parameter :) Statistics is represented as json

**Comment by mtmtmt123** [comment]
Thank you, Have checked but no see this, i look again

**Comment by mtmtmt123** [comment]
Is there an android app to view this via Network?

**Comment by andru-kun** [comment]
> Is there an android app to view this via Network?

Nope :)
