### ISSUE TITLE
glt-algos

### ISSUE THREAD

**Issue by MaynardMiner** [andru-kun/wildrig-multi#9]
SUCCESS: Specified value was saved.

SUCCESS: Specified value was saved.

SUCCESS: Specified value was saved.

SUCCESS: Specified value was saved.
 * VERSIONS:     WildRig/0.15.2.2 beta libuv/1.21.0 OpenCL/2.0 MSVC/2015
 * CPU:          Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz x64 AES-NI
 * ALGO:         glt-jeonghash
 * POOL #1:      jeonghash.mine.zergpool.com:8660
 * API PORT:     60050
 * COMMANDS:     'h' hashrate, 'p' pause, 'r' resume
[00:07:02] donation: 2%
[00:07:02] strategy: 0
[00:07:02] send-stale: no
[00:07:02] watchdog: disabled
[00:07:02] good-risers: default
[00:07:02] initializing GPUs...
[00:07:02] GPU #0 [BusID: #4] [gfx900] Radeon RX Vega
[00:07:02] threads: 1, intensity: 18, worksize: 0/256, cu: 64, memory: 8176Mb

It seems like the latest version is hanging here for all the glt algos on default settings.

Believe it or not, they are actually somewhat relevant since zergpool opened them up on the profit-switching circuit.

The last version did not do that (albeit it had a high rejection rate).

**Comment by MaynardMiner** [comment]
I found it was doing it to more algos after this.

When I set --opencl-threads 2, it fixes it.

I am closing, as I know solution.

**Comment by andru-kun** [comment]
@MaynardMiner hmm, can't reproduce. Can you please specify command line you were running first time? New feature with auto-configuration still need some work, so I want to fix any issue with it.

**Comment by MaynardMiner** [comment]
Just pool, algo, and pass.

Its weird, as it didn't happen to all the algos while benchmarkinh. It started at glt algos, then timetravel before I tried --opencl-threads.

It was my test rig, so it has 1 vega, 1 rtx card, 1 nvidia 1050ti... I use it to fast benchmark miners while coding.

**Comment by andru-kun** [comment]
@MaynardMiner can you please try latest 0.15.3.3 build?

**Comment by MaynardMiner** [comment]
yes will do

**Comment by MaynardMiner** [comment]
It performs fine, latest beta release so far.

However, I am having a new issue:


C:\Users\Mayna\Documents\GitHub\SWARM\bin\wildrig-1>CMD /r powershell -ExecutionPolicy Bypass -command ".\swarm-start.ps1"

SUCCESS: Specified value was saved.

SUCCESS: Specified value was saved.

SUCCESS: Specified value was saved.

SUCCESS: Specified value was saved.
 * VERSIONS:     WildRig/0.15.3.7 beta libuv/1.21.0 OpenCL/2.0 MSVC/2015
 * CPU:          Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz x64 AES-NI
 * ALGO:         x17
 * POOL #1:      mine.nlpool.nl:3737
 * API PORT:     60050
 * COMMANDS:     'h' hashrate, 'p' pause, 'r' resume
[14:36:43] donation: 2%
[14:36:43] strategy: 0
[14:36:43] send-stale: no
[14:36:43] watchdog: disabled
[14:36:43] good-risers: default
[14:36:43] initializing GPUs...
[14:36:43] GPU #0 [BusID: #4] [gfx900] Radeon RX Vega
[14:36:43] threads: 1, intensity: 18, worksize: 0/256, cu: 64, memory: 8176Mb
[14:36:44] GPU #1 [BusID: #7] [Ellesmere] Radeon RX 580 Series
[14:36:44] threads: 1, intensity: 18, worksize: 0/256, cu: 36, memory: 8192Mb
[14:36:44] use pool mine.nlpool.nl:3737 37.97.148.187
[14:36:44] Stratum set difficulty to 0.5000
[14:36:44] new job from mine.nlpool.nl:3737 diff 2.15G
[14:36:59] new job from mine.nlpool.nl:3737 diff 2.15G
[14:37:16] accepted (1/0) avg. effort 34.53% GPU#0 (203 ms)
[14:37:20] new job from mine.nlpool.nl:3737 diff 2.15G
[14:37:27] new job from mine.nlpool.nl:3737 diff 2.15G
[14:37:47] speed 10s/60s/15m 8311 24112 n/a kH/s max: 24183 kH/s
[14:37:48] new job from mine.nlpool.nl:3737 diff 2.15G
[14:38:04] Ctrl+C received, exiting

Then it doesn't exit.

Would this be a driver thing? I am using 19.1.1.

I have already discovered talking to tede (created overdriveNtools) that the API methods for drivers on the ADL side has changed, a lot.

```
      "setx GPU_MAX_HEAP_SIZE 100", 
      "setx GPU_USE_SYNC_OBJECTS 1", 
      "setx GPU_SINGLE_ALLOC_PERCENT 100", 
      "setx GPU_MAX_ALLOC_PERCENT 100"
```

is what I am using as environment.

GPUs enableulps is off
GPUs crossfireautolink is off.
GPUs are set to compute mode.
GPUs enableblockchainsupport (new feature it seems in 19.1.1) is on.

I run application in a powershell window, if it matters. It happens both with Sighup exit and Ctrl+C

**Comment by MaynardMiner** [comment]
It's not driver related. I tried an older driver.

I wonder why it is happening for me. Seems to hash/run fine. It just it locks up on close.

![image](https://user-images.githubusercontent.com/38481606/52526051-0488fa80-2c81-11e9-8e0e-155f62d5284a.png)

**Comment by MaynardMiner** [comment]
I think its my test rig.

The older versions used to close fine from what I remember, and I tried 0.13.6 version, and it still locked up on close, with older drivers.

**Comment by MaynardMiner** [comment]
When I unplug the Vega-

It closes normally.

So either there is something messed up with my Vega, or there is an issue closing when a vega is attached.

I am laying odds it may be my Vega and/or riser. I am going to try to migrate everything, and retest later.

It's just weird that it hashes fine, and the only issue is closing.

**Comment by andru-kun** [comment]
try to enable Gen1 on mobo for PCI-E. When I use different cards in one PC(like RX580 and Vega) and Gen2/Gen3 enabled - I get bunch of bugs right from nowhere %)

**Comment by MaynardMiner** [comment]
I will try, but I noticed something else, after spending considerable amount of time (I have to, so I have answers for users).

The latest AMD driver install now wipes OpenCL.

You used to be able to install Nvidia drivers, then AMD drivers, and both would show up as valid platforms in ``clinfo``.

With 19.1.1- If you install AMD, it wipes the all NVIDIA opencl information. If you install NVIDIA, it wipes AMD opencl, effectively creating all sorts of issues/implications. At least this is happening for me. I have been looking for a way to fix this now, but so far it looks like new drivers are making it impossible to cross-platform.

It sucks, because so far with 19.1.1 and enable KMD_blockchainsupport in registry which is new, it seems to perform better for AMD.

**Comment by MaynardMiner** [comment]
I've benchmarked through all of them-

It's all good.
