### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by mtmtmt123** [andru-kun/wildrig-multi#90]
Hello can you write a command that if the hashrate go to 0 miner restart? i have the problem with obtc
thanks

**Comment by andru-kun** [comment]
if you use nvidia gpu's you can use --watchdog parameter. Just be sure you are using default bat with loop in it

**Comment by OzzSZ** [comment]
Hello, is there any estimate on developing the use of infinity cache on RDNA2 GPUs (RX 6000 series) for ghostrider? It would make them very viable against CPU mining. Thanks for all the effort, keep up the excellent work!

**Comment by andru-kun** [comment]
> Hello, is there any estimate on developing the use of infinity cache on RDNA2 GPUs (RX 6000 series) for ghostrider? It would make them very viable against CPU mining. Thanks for all the effort, keep up the excellent work!

Problem is there is no documentation how to control it
