### ISSUE TITLE
Intensity

### ISSUE THREAD

**Issue by mtmtmt123** [andru-kun/wildrig-multi#96]
Hello how can i change intensity and to how much max?
**thank you very much**
--opencl-launch=IxW  this? and how can i use it?

what is the xW? worksize is for? or can i use only first for intensity and worksize nothing for default?
i mean so intensity 27 --opencl-launch=27
what is max worksize and what is better?

**Comment by andru-kun** [comment]
Not all algorithms are sensitive to worksize change. E.g. ghostrider is not. Also you can use intensity without worksize, miner will use default one.

**Comment by mtmtmt123** [comment]
what is max number of instensity?

**Comment by andru-kun** [comment]
31. And Heavyhash is also not sensetive to worksize )

**Comment by mtmtmt123** [comment]
is more  intesity good for heavyh? what make more intensity better or not better? Gpu work more?

**Comment by andru-kun** [comment]
not always, but you can try and find out if hashrate is higher :)

**Comment by mtmtmt123** [comment]
`thanks have a good weekend
