### ISSUE TITLE
new 31.0 fees

### ISSUE THREAD

**Issue by mtmtmt123** [andru-kun/wildrig-multi#97]
One one rig i have only 1%fee on 2 rigs 2% fees (hhalgo)
all are nvidia rtxs you have to set your tool right
@andru-kun

**Comment by andru-kun** [comment]
this mentioned in release notes :)

**Comment by mtmtmt123** [comment]
i will say you that on one rig to low fees @andru-kun

**Comment by mtmtmt123** [comment]
![fees](https://user-images.githubusercontent.com/93097424/143777722-e67ab6e2-caf9-4e1d-b014-566fcab15e17.jpg)

**Comment by mtmtmt123** [comment]
oh sorry now i read this first 1% than next column i read 2% SORRY 👎

**Comment by andru-kun** [comment]
> oh sorry now i read this first 1% than next column i read 2% SORRY 👎 Good Job Thank you

yeah, miner just searching for NVIDIA gpu', and when find it - increases the dev-fee :)
