### ISSUE TITLE
Unable to get the hashrate on version 0.31.0

### ISSUE THREAD

**Issue by Nicolas-Gong** [andru-kun/wildrig-multi#98]
![image](https://user-images.githubusercontent.com/23067153/143797399-44306b60-8ced-4c75-a5cf-77d7b2aec995.png)

param：
./wildrig.exe --print-full --algo ghostrider --url stratum+tcps://us.flockpool.com:5555 --user xxxxxxx.abc --pass x

**Comment by andru-kun** [comment]
What gpu is that? If some old nvidia, try --opencl-launch 256

**Comment by morphers82** [comment]
I am also getting this error on AMD R9 200 Series GPUs with 4096mb ram.

**Comment by Nicolas-Gong** [comment]
> What gpu is that? If some old nvidia, try --opencl-launch 256

Thank you. It works

**Comment by morphers82** [comment]
> I am also getting this error on AMD R9 200 Series GPUs with 4096mb ram.

Why was this closed?

**Comment by Nicolas-Gong** [comment]
> > I am also getting this error on AMD R9 200 Series GPUs with 4096mb ram.
> 
> Why was this closed?

Because of using --opencl-launch 256 to get the hashrate.
